### PR TITLE
Preserve leading whitespace in fenced blocks in doc comments

### LINKED ISSUE #3370: [Bug]: JSON Schema emitter drops indentation of fenced code blocks inside of doc comments (`/** */`)
### Describe the bug

See reproduction below.

### Reproduction

Take this `main.tsp` TSP file as an example.
```jsonc
/**
 * ```toml
 * deny = [
 *     { name = "simple" },
 *     { name = "simple", version = "*" },
 *     { name = "simple", wrappers = ["example"] }
 * ]
 * ```
 */
@jsonSchema("my-domain.ua")
scalar PackageSpec extends string;
```
Run `tsp compile .` with the JSON schema emitter configured.
Then you'll get the following output:
```yml
type: string
description: |-
  ```toml
  deny = [
  { name = "simple" },
  { name = "simple", version = "*" },
  { name = "simple", wrappers = ["example"] }
  ]
  ```
$schema: https://json-schema.org/draft/2020-12/schema
$id: my-domain.ua
```
Notice how indentation inside of the TOML fenced code block got messed up in the `description` field of the schema.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Veetaha**
Fixes #3370.

This also updates the generated documentation and typescript code to fix lack of indentation on existing fenced blocks in this repo.

### CODE REVIEW

File: packages/compiler/src/core/parser.ts [hunk 1]
```diff
@@ -2815,11 +2815,32 @@ function createParser(code: string | SourceFile, options: ParseOptions = {}): Pa
...
-          if (parseOptional(Token.Star)) {
+          if (!parseOptional(Token.Star)) {
+            break;
+          }
+          if (!inCodeFence) {
             parseOptional(Token.Whitespace);
             start = tokenPos();
             break;
           }
+          // If we are in a code fence we want to preserve the leading whitespace
```
Comment (Veetaha) [inline packages/compiler/src/core/parser.ts:2826]: Here is the fix itself. Everything else is either generated code or tests

File: packages/compiler/src/core/parser.ts [hunk 2]
```diff
@@ -2815,11 +2815,32 @@ function createParser(code: string | SourceFile, options: ParseOptions = {}): Pa
...
+          // /**
+          //  *```
+          //  *foo-bar
+          //  *```
+          //  */
+          //
+          // Not having space after the star isn't idiomatic, but we support this.
+          // `whitespaceStart + 1` strips the first space before `foo-bar` if there
+          // is a space after the star (the idiomatic case).
+          start = Math.min(whitespaceStart + 1, tokenPos());
```
Comment (timotheeguerin) [inline packages/compiler/src/core/parser.ts:2843]: Is that case not going to unindent the  folllowing scenario by 1
````ts
/**
 *```
 *foo
 *  indented
 * ```
 */
 
````

Comment (timotheeguerin) [reply packages/compiler/src/core/parser.ts:2843]: If I look at what TypeScript does it seems to keep 2 space indentation in this case 
image
Might need keep the   ``` index

**Review by timotheeguerin — APPROVED** [review]
Thanks for the contribution! this looks good, talked with the Team.
