### PR TITLE
Change behavior of `--config` to not search for `tspconfig.yaml`

### LINKED ISSUE #2282: Should `--config` allow a directory
I was under the impression that `--config` was supposed to be the path to a config file but it seems like(minus this bug https://github.com/microsoft/typespec/pull/2278) that if you pass a directory it will lookup for `tspconfig.yaml` at that path as well as looking up if there is none.

This feels like an unexpected behavior to me

### PR DESCRIPTION
**Pull request by tjprescott**
Fix #2282.

**TODO**
- [x] test with CLI

### CODE REVIEW

File: packages/compiler/src/config/config-loader.ts [hunk 1]
```diff
@@ -21,7 +21,8 @@ export const defaultConfig = deepFreeze({
  */
 export async function findTypeSpecConfigPath(
   host: CompilerHost,
-  path: string
+  path: string,
+  recurseDirectory: boolean
```
Comment (timotheeguerin) [inline packages/compiler/src/config/config-loader.ts:25]:
```suggestion
  lookup: boolean
```

File: packages/compiler/src/config/config-loader.ts [hunk 2]
```diff
@@ -21,7 +21,8 @@ export const defaultConfig = deepFreeze({
  */
```
Comment (timotheeguerin) [inline packages/compiler/src/config/config-loader.ts:21]: The doc for this function seems a little inaccurate with this new behavior, should maybe be updated or split in 2 functions

File: packages/compiler/src/config/config-loader.ts [hunk 3]
```diff
@@ -61,9 +66,10 @@ export async function findTypeSpecConfigPath(
 export async function loadTypeSpecConfigForPath(
   host: CompilerHost,
   path: string,
+  recurseDirectory: boolean,
```
Comment (timotheeguerin) [inline packages/compiler/src/config/config-loader.ts:69]:
```suggestion
  lookup: boolean,
```

File: packages/compiler/src/core/cli/cli.ts [hunk 4]
```diff
@@ -106,7 +106,7 @@ async function main() {
           .option("config", {
             type: "string",
             describe:
-              "The path to a TypeSpec config YAML file. If a folder is specified, the CLI will attempt to search for 'tspconfig.yaml' by moving up the folder hierarchy. Defaults to {cwd}.",
+              "The path to a TypeSpec config YAML file. If a folder is specified, the CLI will attempt to search for 'tspconfig.yaml' in that folder only. If not specified, it will crawl up the folder hierarchy looking for 'tspconfig.yaml'. Defaults to {cwd}.",
```
Comment (timotheeguerin) [inline packages/compiler/src/core/cli/cli.ts:109]:
```suggestion
              "The path to a TypeSpec config YAML file. If a folder is specified, the CLI will attempt to search for 'tspconfig.yaml' in that folder only. If not specified, it will crawl up the folder hierarchy looking for 'tspconfig.yaml' relative to the entrypoint.",
```

File: packages/compiler/test/config/config.test.ts [hunk 5]
```diff
@@ -15,27 +15,48 @@ const scenarioRoot = resolvePath(
...
+    it("loads 'tspconfig.yaml' if --config {folder} is supplied and tspconfig.yaml is present", async () => {
+      const config = await loadTestConfig("custom", false, true);
+      deepStrictEqual(config, {
+        diagnostics: [],
+        outputDir: "{cwd}/tsp-output",
+        emit: ["openapi"],
+      });
+    });
+
+    it("emits diagnostic if --config {folder} is provided but 'tspconfig.yaml' is not found", async () => {
```
Comment (timotheeguerin) [inline packages/compiler/test/config/config.test.ts:51]: should we have a test for a path that doesn't exists too

File: packages/compiler/src/core/cli/cli.ts (hunk 4 above)
Comment (markcowl) [inline packages/compiler/src/core/cli/cli.ts:109]:
```suggestion
              "The path to a TypeSpec config YAML file, or a folder that contains a 'tspconfig.yaml' file. ",
```

I think discussing the default behavior on this option only confuses the issue.

Comment (tjprescott) [reply packages/compiler/src/core/cli/cli.ts:109]: Per Mark's suggestion, I got rid of the discussion of the default behavior.

File: packages/compiler/src/config/config-loader.ts (hunk 2 above)
Comment (tjprescott) [reply packages/compiler/src/config/config-loader.ts]: I was able to revert these changes while still making all old and new tests pass.

**Review by markcowl — APPROVED** [review]

File: packages/compiler/test/config/config.test.ts [hunk 6]
```diff
@@ -15,8 +16,24 @@ const scenarioRoot = resolvePath(
...
+      lookup: boolean = true,
+      errorIfNotFound: boolean = true
+    ) => {
+      let fullPath = join(scenarioRoot, path);
+      try {
+        const stats = await fs.stat(fullPath);
+        const isDirectory = stats.isDirectory();
+
+        if (lookup === false && isDirectory) {
+          fullPath = join(fullPath, "tspconfig.yaml");
```
Comment (timotheeguerin) [inline packages/compiler/test/config/config.test.ts:30]: do we need to do that? isn't `loadTypeSpecConfigForPath` already dealing with this?

Comment (tjprescott) [reply packages/compiler/test/config/config.test.ts:30]: It does that if you allow it to go and recurse through folders, but since we don't want that behavior, the simplest solution to having to plumb the distinction through a bunch of methods is to simply turn the folder path here into a file path.

Comment (timotheeguerin) [reply packages/compiler/test/config/config.test.ts:30]: I guess I am confused, specially with the latest change which seems to have removed all the lookup disabling behavior

Comment (timotheeguerin) [reply packages/compiler/test/config/config.test.ts:30]: Maybe what needs to be tested for that is the `resolveCompilerOptions` instead of `loadConfigAtPath` as this is what really has the logic for resolving what config to load from which options you pass in the cli
