### PR TITLE
Fix issue with operation parameter versioning

### LINKED ISSUE #2688: "incompatible versioned reference" in function signature
Introduced by #2684.

```
run command:npx --no tsp compile client.tsp --no-emit --warn-as-error
TypeSpec compiler v0.51.0-dev.7

Diagnostics were reported during compilation:

/mnt/vss/_work/1/s/specification/cognitiveservices/OpenAI.Inference/models/completions/chat_completions.tsp:87:3
- error @typespec/versioning/incompatible-versioned-reference: 'Azure.OpenAI.getChatCompletionsWithAzureExtensions'
was added in version 'v2023_08_01_Preview' but contains type 'Azure.OpenAI.(anonymous model).functions' added in
version 'v2023_07_01_Preview'.
> 87 |   functions?: FunctionDefinition[];
     |   ^^^^^^^^^
```
```
run command:npx --no tsp compile client.tsp --no-emit --warn-as-error
TypeSpec compiler v0.51.0-dev.7

Diagnostics were reported during compilation:

/mnt/vss/_work/1/s/specification/eventgrid/Azure.Messaging.EventGrid/main.tsp:315:6
- error @typespec/versioning/incompatible-versioned-reference: 'Microsoft.EventGrid.releaseCloudEvents' is referencing
versioned type 'Microsoft.EventGrid.(anonymous model).releaseDelayInSeconds' but is not versioned itself.
> 315 |   op releaseCloudEvents is StandardOperations.ResourceAction<
      |      ^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by tjprescott**
Fixes #2688.

### CODE REVIEW

File: packages/versioning/src/validate.ts [hunk 1]
```diff
@@ -532,24 +532,6 @@ function validateOperationParameter(
...
-    );
-  } else if (paramTypeAvailability !== undefined) {
-    validateAvailabilityForRef(
-      program,
-      operationAvailability,
-      paramTypeAvailability,
-      operation,
-      parameter.type
-    );
-  }
```
Comment (tjprescott) [inline packages/versioning/src/validate.ts:552]: For this to work, I would actually need to build the availability map based on ALL references in the spec, which would be considerably more design and implementation effort. The new test showcases the problem. Thus, I've just removed this check.

File: packages/versioning/test/versioning.test.ts [hunk 2]
```diff
@@ -912,6 +912,34 @@ describe("versioning: logic", () => {
...
+        
+          @added(Versions.v2)
+          age: Foo;
+        }
+        
+        @added(Versions.v1)
+        op oldOp(...Parameters): void;
+        
+        @added(Versions.v3)
+        op newOp(...Parameters): void;
```
Comment (tjprescott) [inline packages/versioning/test/versioning.test.ts:938]: This is the crux of issue #2688. While this appears to be an error just looking at Parameters and newOp, it makes sense when you consider the existence of oldOp.

**Review by timotheeguerin — APPROVED** [review]
Looks good but Maybe good to verify the build completely fix the spec repo validation before merging
