### PR TITLE
Fix openapi3 emitter to mark request body required

### LINKED ISSUE #1838: The openapi3 emitter does not mark required request bodies with `required: true`
In OpenAPI v3, the request body of an operation can be marked with `required: true` to indicate that the service requires a body to be included in the request.  In TypeSpec, a body parameter that is not optional (not suffixed with "?") should be treated as required and result in `required: true` being specified in the requestBody.  But this isn't happening.

Playground recreate: [link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKbW9kZWwgQW5hbHl6ZUJvZHkgxF53ZWlnaHQ6IGludDMyOwp9CgpAcm91dGUoImHGKiIpIEBwb3N0IG9wIMcTKAogIEBixELEBTrMVAopOiBzdHJpbmc7Cgo%3D)

### PR DESCRIPTION
**Pull request by mikekistler**
This PR fixes the openapi3 generator to add `required: true` to required request bodies.

A test is included to verify that an optional request body is not marked required.

Fixes #1838.

### CODE REVIEW

File: packages/openapi3/src/openapi.ts [hunk 1]
```diff
@@ -1076,6 +1076,7 @@ function createOAPIEmitter(program: Program, options: ResolvedOpenAPI3EmitterOpt
 
     const requestBody: any = {
       description: body.parameter ? getDoc(program, body.parameter) : undefined,
+      required: body.parameter ? !body.parameter.optional : undefined,
```
Comment (timotheeguerin) [inline packages/openapi3/src/openapi.ts:1079]: If there is no body parameter but a body. Wouldn’t then the body be required all the time?

Comment (mikekistler) [reply packages/openapi3/src/openapi.ts]: I didn't realize that the body parameter wasn't present for implicit bodies. I pushed a fix to make implicit bodies required in OpenAPI 3.

**Review by timotheeguerin — APPROVED** [review]
Looks good to me, there is still a sample that need regenration but from testing this looks all expected https://cadlplayground.z22.web.core.windows.net/prs/1906/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQHJvdXRlKCJyZXF1aXJlZC1ib2R5LXBhcmFtIikKb3AgyBlCb2R5UMQXKEDEIyDEBTogQmFyKTogdm9pZMtMb3B0aW9uYWzRTMgZ1Ew%2F103pAJlpbXBsaWNpdMVW7gCcSccbxFgoLi4uzUltb2RlbMRcIHsKICBuYW1lOiBzdHJpbmc7Cn0%3D
