### PR TITLE
Fix bug with renamedFrom resulting in duplicate properties

### LINKED ISSUE #1244: `@renamedFrom` should ensure the old property isn't still present in definition
https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CtIZdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR070BtIdHRw0RVSZXN0OwoKQMdVZWQox0JzKQpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCmVudW0gyFAgxEYidjEiLMUIMsQ7Cgptb2RlbCDHVcQiQGtleSBpZDogc3Ry5QDGICB3ZWlnaHQ6IGludDMyxBFjb2xvcswiQHJl5ACEZEZyb23pAMEudjIsICLFLCIpIHNoYWRlyjR9CgpAZXJyb3LnAIJFxAzlAIFjb8QoyWxtZXNzYWfOOmludGVyZuQA8OYAuecA8iBleHRlbmRzIFJlc291cmNl5AFexQlPcGVyYXTkAJU8xjIsxnE%2BxXJAYWRk6wF5LnYyKcQWZ2V0xAdyb3V0ZSgiY3VzdG9tR2V0IsQdyQ4oKTrnAIXkAJo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

### PR DESCRIPTION
**Pull request by tjprescott**
Fix #1244.

**TODO** 
- [x] Fix for Model Properties
- [x] Fix for union variants
- [x] Fix for enum members
- [x] <del>Evaluate if this is relevant for operations</del> already covered

### CODE REVIEW

File: packages/versioning/src/validate.ts [hunk 1]
```diff
@@ -205,6 +210,74 @@ function validateMultiTypeReference(program: Program, source: Type) {
...
+ */
+function getVersionedNameMap(
+  program: Program,
+  source: Type
+): Map<Version, string | undefined> | undefined {
+  const allVersions = getAllVersions(program, source);
+  if (allVersions === undefined) return undefined;
+
+  const map: Map<Version, string | undefined> = new Map(allVersions.map((v) => [v, undefined]));
+  const availMap = getAvailabilityMap(program, source);
```
Comment (timotheeguerin) [inline packages/versioning/src/validate.ts:224]: Should we compute that map only once and pass it to all the different validator, feels it is a cost that will add up

File: packages/versioning/src/validate.ts [hunk 2]
```diff
@@ -205,6 +210,74 @@ function validateMultiTypeReference(program: Program, source: Type) {
...
+  let lastName: string | undefined = undefined;
+  switch (source.kind) {
+    case "ModelProperty":
+      lastName = source.name;
+      break;
+    case "UnionVariant":
+      if (typeof source.name === "string") {
+        lastName = source.name;
+      } else if (typeof source.name === "symbol") {
+        lastName = source.name.description;
```
Comment (timotheeguerin) [inline packages/versioning/src/validate.ts:249]: I would just ignore if it is a symbol, point of the symbol is it is anonynous

Comment (tjprescott) [reply packages/versioning/src/validate.ts]: Done

File: packages/versioning/src/validate.ts (hunk 1 above)
Comment (tjprescott) [reply packages/versioning/src/validate.ts]: Made that change, but it gets calculated per object (model/enum/union) so I'm not sure it saves a lot of computation.

Comment (tjprescott) [reply packages/versioning/src/validate.ts:224]: So I reverted the change due to the refactoring causing other tests that were passing to fail.

Comment (tjprescott) [reply packages/versioning/src/validate.ts:224]: You can get an availability map for any type (model, model property, enum, union variant, operation, etc.) so while there are multiple cases where we are building this map, each one is for a little specific piece. To be able to calculate "one map to rule them all" so that we would only need to calculate it once and share with all methods would be a major refactor.

**Review by timotheeguerin — APPROVED** [review]
