### PR TITLE
Fix listing files when multiople instance are loaded

### LINKED ISSUE #9313: [Bug]: `tsp compile --list-files` doesn't list files, if spec is outside current directory
### Describe the bug

`tsp compile --list-files` doesn't list files, if the spec is outside the current directory.  The compile itself seems to work fine, just the files are not listed.

### Reproduction

If I run `tsp compile --list-files` on a spec under my current directory, it prints the files as expected:

```
~/specs-mh$ npx tsp compile --list-files specification/contosowidgetmanager/Contoso.Management
TypeSpec compiler v1.7.1

✔ Compiling
✔ @azure-tools/typespec-autorest 565ms specification/contosowidgetmanager/
    specification/contosowidgetmanager/resource-manager/Microsoft.Contoso/preview/2021-10-01-preview/contoso.json
    specification/contosowidgetmanager/resource-manager/Microsoft.Contoso/preview/2021-10-01-preview/examples/Operations_List.json
    ...
Compilation completed successfully.
```

However, if I run the same command on the same spec, but outside my current directory, no files are printed:

```
~/specs-mh$ npx tsp compile --list-files ../specs-mh-2/specification/contosowidgetmanager/Contoso.Management
TypeSpec compiler v1.7.1

✔ Compiling
✔ @azure-tools/typespec-autorest 529ms ../specs-mh-2/specification/contosowidgetmanager/

Compilation completed successfully.
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #9313

### CODE REVIEW

File: packages/compiler/src/core/emitter-utils.ts [hunk 1]
```diff
@@ -8,10 +8,19 @@ export interface EmitFileOptions {
   newLine?: NewLine;
 }
 
-const emittedFilesPaths: string[] = [];
-export function flushEmittedFilesPaths(): string[] {
-  return emittedFilesPaths.splice(0, emittedFilesPaths.length);
+const emittedFilesPerProgramKey = Symbol.for("TYPESPEC_EMITTED_FILES_PATHS");
+if ((globalThis as any)[emittedFilesPerProgramKey] === undefined) {
+  (globalThis as any)[emittedFilesPerProgramKey] = new Map<Program, string[]>();
```
Comment (timotheeguerin) [inline packages/compiler/src/core/emitter-utils.ts]:
```suggestion
  (globalThis as any)[emittedFilesPerProgramKey] = new WeakMap<Program, string[]>();
```

**Review by markcowl — APPROVED** [review]
