### PR TITLE
Show better error when a crash occur in `$onValidate`

### LINKED ISSUE #1120: Log library bug url for failure in `onValidate` and in `decorators`
PR #1106 added support for logging the library bug url when an emitter would fail. The same should happen for onValidate and decorators. 

It is a bit more tricky for those as they can be deeply nested in the loading a library `my-lib` -> `node_modules/my-lib/main.cadl` ->  `node_modules/my-lib/decorators.cadl` -> `node_modules/my-lib/decorators.js`

This means we need to keep some context that we are currently resolving content for a given library and when to reailize we are not anymore(If a library import another for example)
Logic could be:
- when resolving a library set it at the current lib
- when resolving another library while in a library then push the new one to the top of the stack
- when resolving a path outside of the root of the library remove the current lib state.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #1120
Report the bug url if available as well as some version information to help with diagnostic of the bug.
image

Also improved the same error that was already shown when an emitter crashed.

### CODE REVIEW

File: packages/compiler/src/core/binder.ts [hunk 1]
```diff
@@ -137,7 +138,12 @@ export function createBinder(program: Program): Binder {
           name = getFunctionName(key);
           kind = "decorator";
           if (name === "onValidate") {
-            program.onValidate(member as any);
+            const context = getLocationContext(program, sourceFile);
+            const metdata =
```
Comment (markcowl) [inline packages/compiler/src/core/binder.ts:142]:
```suggestion
            const metadata =
```

**Review by markcowl — APPROVED** [review]

File: packages/compiler/src/core/binder.ts [hunk 2]
```diff
@@ -137,7 +138,12 @@ export function createBinder(program: Program): Binder {
           name = getFunctionName(key);
           kind = "decorator";
           if (name === "onValidate") {
-            program.onValidate(member as any);
+            const context = getLocationContext(program, sourceFile);
+            const metadata =
+              context.type === "library"
+                ? context.metadata
+                : ({ type: "file" } satisfies FileLibraryMetadata);
+            program.onValidate(member as any, metdata);
```
Comment (timotheeguerin) [inline packages/compiler/src/core/binder.ts:146]:
```suggestion
            program.onValidate(member as any, metadata);
```
