### PR TITLE
Value world, object, tuple literals, const

### LINKED ISSUE #2046: object, tuple values and the value world
# Values in TypeSpec

## Problem

Currently we have a very limited set of types in TypeSpec that are used as values(`String`, `Number`, `Boolean`) as well as a misuse of other types(`Model` and `Tuple`) in order to fill that gap

For example we might see this in the OpenAPI library:

```tsp
model Info {
  title?: string;
  version?: string;
  contact?: Contact;
}
model Contact { name?: string; email?: string }

extern dec info(target, data: Info);
```

which is then used like this

```tsp
@info({
  title: "My API",
  version: "1.0"
})
```

however previous signature allows other types to be passed as well, for example a union which is in this case not at all what we want

```tsp
@info({
  title: "My API",
  version: "1.0"
} | {
  title: "My API alt",
  version: "2.0"
})
```

## Current state

We currently have a way to request a value instead of a type using `valueof` keyword. This will automatically cast the type to the JS value in a decorator
`valueof` is limited to `string`, `numeric` and `boolean` scalars today

```tsp
extern dec doc(target, value: valueof string);
```

```ts
// Here the value param was marshalled to a JS string
export function $doc(context, target, value: string) {}
```

This introduce the concept of values in the language however as it was limited to `string`, `numeric` and `boolean` scalars the existing `String`, `Number` and `Boolean` types were still used to represent values depending on the context. Those places are:

- Decorator arguments
- Template arguments
- Alias
- Property defaults

## Approved design

A follow up part of the `valueof` [proposal](https://github.com/microsoft/typespec/issues/1745) was to add object literals `#{}` and tuple literals `#[]` to fill the gap of the missing types.
The design allowed property values to be types as well as values.

For example

```tsp
op myOp(): void;

@foo(#{
  title: "My API",
  operation: myOp,
})
```

### Distinction of values and types

As shown before the current state reuse the same types for values and types. However with the introduction of object and tuple literal we are now having some new entities that are only meant to be used as values.

| Entity Name          | Type | Value |
| -------------------- | ---- | ----- |
| `Namespace`          | ✅   |       |
| `Model`              | ✅   |       |
| `ModelProperty`      | ✅   |       |
| `Union`              | ✅   |       |
| `UnionVariant`       | ✅   |       |
| `Interface`          | ✅   |       |
| `Operation`          | ✅   |       |
| `Scalar`             | ✅   |       |
| `Tuple`              | ✅   |       |
| `Enum`               | ✅   |       |
| `EnumMember`         | ✅   | ✅    |
| `StringLiteral`      | ✅   | ✅    |
| `NumberLiteral`      | ✅   | ✅    |
| `BooleanLiteral`     | ✅   | ✅    |
| `ObjectLiteral`      |      | ✅    |
| `TupleLiteral`       |      | ✅    |
| ---- _intrinsic_ --- | ---  | ---   |
| `null`               | ✅   | ✅    |
| `unknown`            | ✅   |       |

#### Object and Tuple literals only accept other values

In order to make sure that types and value stay separated we need to make sure that object and tuple literals only accept other values as their properties/values.
This mean this example would produce an error

```tsp
op myOp(): void;

@foo(#{
  title: "My API",
  operation: myOp,
})
```

> If this is a behavior we want to add in the future we could add a special template type that explicitly define a reference to a type.
>
> ```tsp
> @foo(#{
>   title: "My API",
>   operation: Ref<myOp>,
> })
> ```

#### Contexts

There is 3 context that can exists in TypeSpec:

- **Type only** This is when an expression can only be a Type.
  - Model property type
  - Array element type
  - Tuple values
  - Operation parameters
  - Operation return type
  - Union variant type with some exceptions when used as a decorator or template parameter constraint.
- **Value only** This is when an expression can only be a Value.
  - Default values
- **Type and Value Constaints** This is when an expression can be a type or a `valueof`
  - Decorator parameters
  - Template parameters
- **Type and Value** This is when an expression can be a type or a value.
  - Aliases
  - Decorator arguments
  - Template arguments

### What does this mean?

1. You cannot assign a value to something not marked with `valueof`

```tsp
{} =>  {} // ok
{name: string} | {} =>  {} // ok
#{} => {} // error
```

2. You cannot a type to something marked with `valueof`

```tsp
{} => valueof {} // error
#{} => valueof {} // ok
```

3. If you want to accept both you have to be explicit in allowing `x | valueof y` (e.g. `unknown | valueof unknown` to allow any type or any value, or `{} | valueof {}` to any type assignable to `{}` or any object value)
4. Property default should only accept values
5. Decorators will only marshall values (if possible) to JS types.

### `const` statements

In order to separate values from types we need to have a new equivalent to `alias`(meant for types) for values. This is where `const` comes in.

#### Syntax:

```ts
const identifier[: Type] = Value;
```

#### Example:

```ts
// Implicit type
const myValue = "Hello, World!";
// Explicit type
const myValue: string = "Hello, World!";
const myValue: Abc = #{name: "John", age: 30};
```

#### Evaluation:

`const` like alias are evaluated in the reference order not in the declaration order.

This means for example the following is valid:

```ts
const a = b;
const b = "foo";
```

This is needed as we are merging namespace, passing values to decorators which are not evaluated in the declaration order and this would cause all kinda of issues.

### Scalar constructors

For primitives scalars(numeric, string, boolean) we can infer the type from a literal in most cases but for other scalars we can't know how to instantiate them, or sometimes it is ambiguous which primitive scalar a literal should be.

#### Primitive scalar constructors

This only apply to scalars that extends `numeric`, `string` or `boolean`(Not sure we need this one)
As for those scalars are the base of every other values we do have to treat them specially. This mean they have a default constructor that will take their value.

- `string` for string scalars
- `Numeric` for numeric scalars
- `boolean` for boolean scalars

```ts
const a = int16(123);
const b = string("abc");
const c = myFormattedString("abc");
```

### Scalars named constructors

For other scalars as we cannot define a syntax to create every possible scalar we can instead allow scalars to define constructor in their body which can then be used to instantiate that scalar with the given values.
The constructor can be defined with the `init` (or `new` open for either) keyword.

Those constructors do not actually instantiate the scalar with those values behind the scene they more keep reference of the parameters given to it so an emitter can convert that constructor into their coresponding language scalar initialization.

For example the `utcDateTime` scalar could look something like that

```ts
scalar utcDateTime {
  init fromISO(value: string);
  init fromDate(value: {year: int32, month: int8, day: int8, hour: int8, minute: int8, second: int8, millisecond: int16});
  init now();
}
```

And could then be used like this

```ts
model User {
  createdAt: utcDateTime =  utcDateTime.now();
  expire: utcDateTime =  utcDateTime.fromDate({year: 2100});
  cleanup: utcDateTime =  utcDateTime.fromISO("2025-01-01T01:01:01");
}
```

#### Scalars

Whenever a value type is declared it is resolved against the constraint to see what type it is.

##### Single type case

```ts
const a: int8 = 123; // a is now a ScalarValue with type int8
model Foo {
  prop?: int32 = 123; // prop default is now a ScalarValue with type int32
}
```

##### Multiple type non-ambiguous case

```ts
const a: int8 | string = 123; // a is now a ScalarValue with type int8, it cannot be a string
```

##### Multiple type ambiguous case

When a value is assigned to multiple type and it is not clear which type it should be, it is a compile error.

```ts
const a: int8 | int32 = 123; // it is ambiguous if 123 should be an int8 or int32 as it could be both. This is a compile error.

// instead you have to be explicit in those cases
const a: int8 | int32 = int8(123);
```

##### Implicit type

If the target has no type then we just keep it as a XLiteralValue and keep the precise type. It might get assigned a scalar type next time it reach a constraint.

```ts
const a = 123; // a is now a NumericLiteralValue
```

#### Models

As models are structural in the type there is never a defined model assigned to an object literal. It takes the format of whatever is its current assigned type.

For example given the following models

```tsp
model Info {
  title?: string;
  version?: int32;
}

model InfoWithExtra {
  ...Info;
  extra?: string
}
```

```ts
// Type of implicit is the exact type `{a: "foo", b: 123}`
const implicit = #{
  a: "foo",
  b: 123
}

const info: Info = implicit; // Now the type of info is just `Info` there is no reference back to the original type.
const infoWithExtra: InfoWithExtra = info; // Now the type of info is just `InfoWithExtra` there is no reference back to the Info type.
```

##### Scalars in models

In the same way as scalar works, scalars in models will need to resolve what type they are. Either by being explicit or implicitly resolving from the property scalar type. This also mean that if a property has ambiguous scalars then it will be an error

```ts
const a: {foo: int32}  = #{a: 123} // a.foo is an int32
const a: {foo: int32 | int64}  = #{a: 123} // error we can't know which numeric to use
```

### Internals

```ts
type Value =
  | ScalarValue
  | NumericValue
  | StringValue
  | BooleanValue
  | ObjectValue
  | ArrayValue
  | EnumMemberValue
  | NullValue;

interface ValueBase {
  valueKind: string;
  type: Type; // Every value has a type. That type could be something completely different(much wider type)
}

interface ObjectValue extends ValueBase {
  valueKind: "ObjectValue";
  type: Model | Union;
  properties: Map<string, ObjectValuePropertyDescriptor>;
}

interface ObjectValuePropertyDescriptor {
  valueKind: "ObjectProperty";
  name: string;
  value: Value;
}

interface ArrayValue extends BaseValue {
  valueKind: "ArrayValue";
  length: number;
  values: Value[];
}

interface ScalarValue extends BaseValue {
  valueKind: "ScalarValue";
  scalar: Scalar; // We need to keep a reference of what scalar this is.
  value: { name: string; args: Value[] }; // e.g. for utcDateTime(2020,12,01)
}
interface NumericValue extends BaseValue {
  valueKind: "NumericValue";
  scalar: Scalar | undefined;
  value: Numeric;
}
interface StringValue extends BaseValue {
  valueKind: "StringValue";
  scalar: Scalar | undefined;
  value: string;
}
interface BooleanValue extends BaseValue {
  valueKind: "BooleanValue";
  scalar: Scalar | undefined;
  value: boolean;
}

interface Numeric {
  (value: string): Numeric;
  /** Return the value as number. @throws if the value is not representable as number */
  asNumber(): number;
  asBigInt(): BigInt; // ?
  asString(): string;
  equals(value: Numeric): boolean;
  gt(value: Numeric): boolean;
  lt(value: Numeric): boolean;
  gte(value: Numeric): boolean;
  lte(value: Numeric): boolean;
}

interface EnumMemberValue extends BaseValue {
  valueKind: "EnumMemberValue";
  value: EnumMember;
}

interface NullValue extends BaseValue {
  valueKind: "NullValue";
}
```

### Accessing object or tuple literal properties

Things like this are not part of this proposal as it would involve designing optionality in values which doesn't seem necessary at this time and add more complexity to this already large proposal.

```ts
const a = #{name: "Abc"}
const b = a.name;
```

#### Library authors

There is only 3 locations where values can get exposed to a library author

1. **Decorator arguments**: For this one we already receive the JS primitive values when using `valueof` this would now also make it that we receive the JS object/array in the case of object and tuple values and null for `NullValue`. For `EnumMemberValue` user would still receive it as that type as there is no equivalent.
2. **Property default**: This one is tricky as currently you would get the types that can also be values but here ideally the type would be the `Value` type defined above but this would be a breaking change. We can however add a new `defaultValue: Value` property and deprecate the existing `default` property(which wouldn't be set in the case of object and array values but keep working as before in the other cases).
3. **Template arguments**: This one is not really something that emitters would usually dig into as templates are already instantiated. So in this case it would just mean that there is additional types that you might receive which is just breaking in the TypeScript compilation but not in the JS code - Like adding any new type to the compiler.

#### Spec authors

For spec authors the breaking changes are minimal, the only issue is that we used to allow tuples to be used as default values. However now those should be done with tuple literals.

To make this change non breaking we can allow with a deprecation warning tuple and models to be automatically casted to array and object values. For object this is not covering anything we supported before however allowing that would allow our libraries to migrate to using `valueof` which would then show a deprecated warning to the user which can be automatically resolved by a codefix.

Kapture 2024-03-18 at 19 31 32

### PR DESCRIPTION
**Pull request by timotheeguerin**
resolves #2046    [Playround](https://cadlplayground.z22.web.core.windows.net/prs/3022/)

Add the new syntax for object literals using `#{`. For this first version an object literal can only contain other object literal and other literals(string, number, boolean)) 

## Values axioms
1. `alias` always produces a type. If you attempt to alias a value, you get an error.
2. A string template produces a string template type if all substitutions are types, and a value if all substitutions are numeric, boolean, or string values. A mixture of types and values is an error.
3. The string literal syntax always results in a string literal type
4. A string literal type may be passed as a string value when the signature expects a value. When the signature expects either a string literal type or a string value, it is passed as a string value.
5. A string template type can be passed as a string value when all its substitutions are string literal types.

### Removal of the `ValueType` replacement with `MixedConstraint`

This shouldn't affect anyone as you were only exposed to this if you digged into the template parameter and looked at the constraint 

## Using a tuple instead of a tuple literal
- ✅ still work
- emit a warning
image

- provide a codefix
image

## Using a model expression instead of an object literal
This technically didn't work before(different from above where tuple was used as a value) but allow this will allow us to convert most of our decorators to use `valueof` without being breaking
Kapture 2024-03-18 at 19 31 32

## Old decorator marshalling

If a library had a decorator with `valueof` one of those types `numeric`, `int64`, `uint64`, `integer`, `float`, `decimal`, `decimal128`, `null` it used to marshall those as JS `number` and `NullType` for `null`. With the introduction of values we have a new marshalling logic which will marshall those numeric types as `Numeric` and the others will remain numbers. `null` will also get marshalled as `null`.

For now this is an opt-in behavior with a warning on decorators not opt-in having a parameter with a constraint from the list above.

Example: 
```
extern dec multipleOf(target: numeric | Reflection.ModelProperty, value: valueof numeric);
```
Will now emit a deprecated warning because `value` is of type `valueof string` which would marshall to `Numeric` under the new logic but as `number` previously.

To opt-in you can add the following to your library 
```ts
export const $flags = defineModuleFlags({
  decoratorArgMarshalling: "value",
});
```

### CODE REVIEW

File: packages/compiler/src/core/checker.ts [hunk 1]
```diff
@@ -2948,6 +2954,79 @@ export function createChecker(program: Program): Checker {
...
+  function checkObjectSpreadProperty(
+    targetNode: TypeReferenceNode,
+    mapper: TypeMapper | undefined
+  ): ObjectLiteralProperty[] {
+    const targetType = getTypeForNode(targetNode, mapper);
+
+    if (targetType.kind === "TemplateParameter" || isErrorType(targetType)) {
+      return [];
+    }
+    // TODO: instanceof is because of conflict of the Object type from projection.
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:3020]: resolve todo

File: packages/compiler/src/core/checker.ts [hunk 2]
```diff
@@ -2948,6 +2954,79 @@ export function createChecker(program: Program): Checker {
...
+    if (targetType.kind !== "Object" || !(targetType.properties instanceof Map)) {
+      reportCheckerDiagnostic(createDiagnostic({ code: "spread-object", target: targetNode }));
+      return [];
+    }
+
+    // TODO: do we want to clone or use the exact same reference here?
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:3026]: resolve todo

File: packages/compiler/src/core/checker.ts [hunk 3]
```diff
@@ -5190,7 +5269,8 @@ export function createChecker(program: Program): Checker {
 
     switch (base.kind) {
       case "Object":
-        return base.properties[member] || errorType;
+        // TODO: resolve conflict here
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:5272]: resolve todo

File: packages/compiler/src/core/messages.ts [hunk 4]
```diff
@@ -391,19 +391,38 @@ const diagnostics = {
...
+  "spread-object": {
+    severity: "error",
+    messages: {
+      default: "Cannot spread properties of non-object type.",
+    },
+  },
+  "not-literal": {
+    severity: "error",
+    messages: {
+      default: "Type must be a literal type.", // TODO: better message? Goal here is to say you needed to use another literal type inside a literal object or tuple.
```
Comment (timotheeguerin) [inline packages/compiler/src/core/messages.ts:410]: Todo better message idea?

File: packages/compiler/src/core/types.ts [hunk 5]
```diff
@@ -109,6 +111,8 @@ export type Type =
   | Decorator
   | FunctionParameter
   | ObjectType
+  | ObjectLiteral
+  | TupleLiteral
```
Comment (timotheeguerin) [inline packages/compiler/src/core/types.ts:115]: Would be good to review the naming

File: packages/compiler/src/core/checker.ts [hunk 6]
```diff
@@ -2948,6 +2971,90 @@ export function createChecker(program: Program): Checker {
...
+  }
+
+  function checkTupleLiteral(node: TupleLiteralNode, mapper: TypeMapper | undefined): TupleLiteral {
+    const values = node.values
+      .map((itemNode) => {
+        const type = getTypeOrValueForNode(itemNode, mapper);
+        if (checkIsLiteralType(type, itemNode)) {
+          return type;
+        } else {
+          return undefined; // TODO: do we want to omit this or include an error type?
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:3047]: todo, what should happen in those cases?

We could omit the type which would allow further check to keep moving as long as where it was used didn't depend on the order. Or we make it the errorType and that fails

**Comment by bterlson** [comment]
Some thoughts on the design of values in general (I think these are reflected, but just putting things into spec form).

Overall, it seems very important to separate types and values as cleanly as possible. It's tempting to have things serve as both depending on context, but this can cause significant confusion. For example, unions outside of signatures of decorators and templates should not allow both types and values, and most type references should not allow values, e.g. a model property like `prop: #{}` should be an error..

That said, there are exceptions. For example, certain literals can represent types or values (referred to as valuish types for want of a better word):

* string literals - either a string literal type whose only assignable value is a string with that value, or a string of that value.
* numeric literals - either a numeric literal type whose only assignable value is a number of with value, or a number of that value. Note also that numeric literals are often coerced to either a type or value of a numeric subtype depending on context.
* boolean literals - either a boolean literal type whose only assignable value is that boolean, or a true/false value.
* enum members - either an enum member type, or a value of that enum member's value.

It is often not ambiguous whether the string or value is required. For example, default values are always values, type references like the type of a model property are always types.

However, it is possible to define a parameter to a template or decorator signature that creates this ambiguity. Consider a decorator with a parameter of type `string | valueof string`. If we pass `"hello"`, we are not sure if we are passing the string literal type or the string literal value.

We could say this is not a problem, but I believe it can be - types can carry additional metadata on them that a decorator may want to access. Notably, enum member types contain a reference to their container, whereas the enum value is just a string/number.

We could introduce new syntax to represent either the value or type versions, but this would be deeply annoying.

We could say that it's an error to declare such a signature, but `@extension` is a common decorator where you want to allow any type or any value, because you want to allow both pushing literal JSON into e.g. a JSON Schema, but also pushing a type as a schema. For example, `@extension("is-thing", true)` should emit `"is-thing", true`, `@extension("itemSchema", string)` should emit `"itemSchema: { "type": "string" }`.

A proposal that might work: valueish literals/references are always passed as value in situations where there is any ambiguity, and we provide a mechanism to explicitly pass as type when required (discussed in next section).

## ValueType<T extends valueof unknown>

A template that takes a value and returns a type whose only allowable value is exactly the provided value. For example:

* `ValueType<10>`: the numeric type literal 10.
* `ValueType<SomeEnum.value>`: the enum member type.
* `ValueType<#{ x: 1, y: 1}>`: The model type `{x: 1, y: 1}`.

This allows disambiguating what the meaning of `"foo"` is when using `@extension`: `@extension("itemSchema", ValueType<"foo">)` emits `"itemSchema: { "type": "string", "const": "foo" }`..

File: packages/compiler/src/core/messages.ts (hunk 4 above)
Comment (bterlson) [reply packages/compiler/src/core/messages.ts:410]: `Expected a value, but found a type.`?

File: packages/http/lib/auth.tsp [hunk 7]
```diff
@@ -111,7 +111,7 @@ model ApiKeyAuth<Location extends ApiKeyLocation, Name extends string> {
  * @template Scopes The list of OAuth2 scopes, which are common for every flow from `Flows`. This list is combined with the scopes defined in specific OAuth2 flows.
  */
 @doc("")
-model OAuth2Auth<Flows extends OAuth2Flow[], Scopes extends valueof string[] = []> {
+model OAuth2Auth<Flows extends OAuth2Flow[], Scopes extends string[] = []> {
```
Comment (timotheeguerin) [inline packages/http/lib/auth.tsp:114]: Should we add `valueof` again, even after resolving the breaking change that would give warning to everybody. This might be better to do as a seperate PR that would change all our decorators to go to value

File: packages/http/lib/auth.tsp [hunk 8]
```diff
@@ -111,7 +111,7 @@ model ApiKeyAuth<Location extends ApiKeyLocation, Name extends string> {
...
   @doc("OAuth2 authentication")
   type: AuthType.oauth2;
```
Comment (timotheeguerin) [inline packages/http/lib/auth.tsp:116]: Should `valueof string[]` be assignable to `string[]`

for example

```
model A<T extends string[]> {}
model B<T extends valueof string[]> is A<T>;
```

Comment (timotheeguerin) [reply packages/http/lib/auth.tsp:116]: Similar question Should `#{}` be assignable to `{}` or `unknown` if that the constraint on a decorator or template param

File: packages/http/lib/auth.tsp (hunk 7 above)
Comment (bterlson) [reply packages/http/lib/auth.tsp:114]: This should be valueof I think. A follow-up PR seems good though.

File: packages/http/lib/auth.tsp (hunk 8 above)
Comment (bterlson) [reply packages/http/lib/auth.tsp:116]: I think based on the principle that types and values should be as distinct as possible, my opinion so far:

> Should valueof string[] be assignable to string[]

No, ideally error on T in `A<T>`.

> Should #{} be assignable to {} or unknown if that the constraint on a decorator or template param

No, would need `valueof {}` or `valueof unknown`.

File: packages/compiler/src/core/types.ts [hunk 9]
```diff
@@ -285,10 +312,22 @@ export interface ModelProperty extends BaseType, DecoratedType {
   // this tracks the property we copied from.
   sourceProperty?: ModelProperty;
   optional: boolean;
-  default?: Type;
+  default?: Type | Value;
   model?: Model;
 }
 
+export interface ObjectLiteral {
```
Comment (bterlson) [inline packages/compiler/src/core/types.ts:319]: I think `ObjectValue` and `TupleValue` could be better names for these.

File: packages/compiler/src/core/types.ts [hunk 10]
```diff
@@ -509,6 +548,13 @@ export interface Tuple extends BaseType {
   values: Type[];
 }
 
+export interface ParamConstraintUnion {
```
Comment (bterlson) [inline packages/compiler/src/core/types.ts:551]: Maybe `EntityUnion`?

File: .chronus/changes/feature-object-literals-2024-2-15-18-36-3.md
Comment (timotheeguerin) [inline .chronus/changes/feature-object-literals-2024-2-15-18-36-3.md:1]: Update changelog to reflect all new proposal

File: packages/compiler/src/core/parser.ts [hunk 11]
```diff
@@ -982,6 +1075,32 @@ function createParser(code: string | SourceFile, options: ParseOptions = {}): Pa
     return undefined;
   }
 
+  function parseScalarMembers(): readonly ScalarConstructorNode[] {
+    if (token() === Token.Semicolon) {
```
Comment (bterlson) [inline packages/compiler/src/core/parser.ts:1079]: I feel like this should be using the parseList helper? It also seems like the behavior of this with respect to empty statements is different from model members (e.g. today `model Foo { ; }` is an error).

File: packages/compiler/src/core/parser.ts [hunk 12]
```diff
@@ -982,6 +1075,32 @@ function createParser(code: string | SourceFile, options: ParseOptions = {}): Pa
...
+    } else {
+      return parseList(ListKind.ScalarMembers, parseScalarMember);
+    }
+  }
+
+  function parseScalarMember(
+    pos: number,
+    decorators: DecoratorExpressionNode[]
+  ): ScalarConstructorNode {
+    reportInvalidDecorators(decorators, "spread property");
```
Comment (bterlson) [inline packages/compiler/src/core/parser.ts:1091]: spread property?

File: packages/compiler/src/core/parser.ts (hunk 11 above)
Comment (timotheeguerin) [reply packages/compiler/src/core/parser.ts:1079]: im doing that no below? This just scan for the `scalar foo;` or `scalar bar extends foo;` cases

File: packages/compiler/test/checker/values/string-values.test.ts [hunk 13]
```diff
@@ -0,0 +1,122 @@
...
+        ["✔", `"abc"`],
+        ["✔", `"one \${"abc"} def"`],
+        ["✘", `123`, "Type '123' is not assignable to type 'string'"],
+      ],
+    ],
+    [
+      `"abc"`,
+      [
+        ["✔", `"abc"`],
+        // ["✔", `"a\${"b"}c"`], // TODO: should that work? it doesn't in main
```
Comment (timotheeguerin) [inline packages/compiler/test/checker/values/string-values.test.ts:110]: Todo should that work

File: packages/compiler/src/core/checker.ts [hunk 14]
```diff
@@ -2599,19 +3048,76 @@ export function createChecker(program: Program): Checker {
...
+    }
+
+    if (hasValue) {
+      let str = node.head.value;
+      for (const [span, typeOrValue] of spanTypeOrValues) {
+        compilerAssert(typeOrValue !== null && isValue(typeOrValue), "Expected value.");
+        str += stringifyValueForTemplate(typeOrValue);
+        str += span.literal.value;
+      }
+      return checkStringValue(createLiteralType(str), undefined, node); // TODO: constraint
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:3084]: todo

File: packages/compiler/src/core/checker.ts [hunk 15]
```diff
@@ -2949,37 +3452,500 @@ export function createChecker(program: Program): Checker {
...
+      value: {
+        name: declaration.name,
+        args: resolvedArgs,
+      },
+      scalar: declaration.scalar,
+      type: declaration.scalar,
+    };
+  }
+
+  // TODO: should those be called eval?
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:3887]: What do we think about naming of the value functions?

File: packages/compiler/src/core/types.ts [hunk 16]
```diff
@@ -308,13 +400,23 @@ export interface Scalar extends BaseType, DecoratedType, TemplatedTypeBase {
...
   symbol?: Sym;
 }
 
+// TODO: should we just call that Constructor or NamedConstructor for future proof?
+export interface ScalarConstructor extends BaseType {
+  kind: "ScalarConstructor";
+  node: ScalarConstructorNode;
+  name: string;
+  scalar: Scalar;
+  parameters: FunctionParameter[];
```
Comment (timotheeguerin) [inline packages/compiler/src/core/types.ts:417]: Should we seperate `FunctionParameters` that is currently used to describe decorators function parmaters and accept `valueof` vs `Scalar Constructor` already infer that it must take in a value.

File: packages/compiler/src/core/types.ts [hunk 17]
```diff
@@ -471,7 +573,8 @@ export interface StringLiteral extends BaseType {
 export interface NumericLiteral extends BaseType {
   kind: "Number";
   node?: NumericLiteralNode;
-  value: number;
+  value: number; // TODO: should we deprecate this?
```
Comment (timotheeguerin) [inline packages/compiler/src/core/types.ts:576]: Todo should we deprecate the old value?

File: packages/compiler/src/core/types.ts [hunk 18]
```diff
@@ -1168,9 +1302,18 @@ export interface ScalarStatementNode extends BaseNode, DeclarationNode, Template
   readonly kind: SyntaxKind.ScalarStatement;
   readonly extends?: TypeReferenceNode;
   readonly decorators: readonly DecoratorExpressionNode[];
+  readonly members: readonly ScalarConstructorNode[];
   readonly parent?: TypeSpecScriptNode | NamespaceStatementNode;
 }
 
+// TODO: should this be ScalarConstructorDeclarationNode?
+export interface ScalarConstructorNode extends BaseNode {
```
Comment (timotheeguerin) [inline packages/compiler/src/core/types.ts:1310]: Name question `ScalarConstructorDeclarationNode`?

File: .chronus/changes/feature-object-literals-2024-2-15-18-36-3.md [hunk 19]
```diff
@@ -0,0 +1,17 @@
+---
+# Change versionKind to one of: internal, fix, dependencies, feature, deprecation, breaking
+changeKind: fix
+packages:
+  - "@typespec/compiler"
+---
+
+New Language Feature: Object and Tuple Literals.
```
Comment (bterlson) [inline .chronus/changes/feature-object-literals-2024-2-15-18-36-3.md:8]: I thought we wanted to call these array literals?

File: .chronus/changes/feature-object-literals-32024-2-15-18-36-3.md [hunk 20]
```diff
@@ -0,0 +1,8 @@
+---
+# Change versionKind to one of: internal, fix, dependencies, feature, deprecation, breaking
+changeKind: fix
+packages:
+  - "@typespec/http"
+---
+
+Update Flow Template to make sure of new tuple literals
```
Comment (bterlson) [inline .chronus/changes/feature-object-literals-32024-2-15-18-36-3.md:8]:
```suggestion
Update Flow Template to make use of the new tuple literals
```

File: docs/language-basics/type-and-values.md [hunk 21]
```diff
@@ -0,0 +1,51 @@
...
+  - Operation parameters
+  - Operation return type
+  - Union variant type with some exceptions when used as a decorator or template parameter constraint.
+- **Value only** This is when an expression can only be a Value.
+  - Default values
+- **Type and Value Constaints** This is when an expression can be a type or a `valueof`
+  - Decorator parameters
+  - Template parameters
+- **Type and Value** This is when an expression can be a type or a value.
+  - Aliases
```
Comment (bterlson) [inline docs/language-basics/type-and-values.md:49]: I think if this is true, values always produce an error?

File: .chronus/changes/feature-object-literals-2024-2-15-18-36-3.md (hunk 19 above)
Comment (timotheeguerin) [reply .chronus/changes/feature-object-literals-2024-2-15-18-36-3.md:8]: yeah I think this is from before, I haven't update those docs

File: docs/language-basics/type-and-values.md (hunk 21 above)
Comment (timotheeguerin) [reply docs/language-basics/type-and-values.md:49]: forgot to update this doc its from before the updated propsal

File: docs/libraries/http/reference/decorators.md
Comment (timotheeguerin) [inline docs/libraries/http/reference/decorators.md:1]: Bug:

```

model M1<T> {}
const c2= "abc";
M1<c2>; // should be an error as we are passing a value to a constraint not explicilty allowing values
```



// model Cases {
//   c1: M1<"abc">;
//   c2: 
//   c3: M1<c2>;
// }

File: packages/compiler/src/core/checker.ts [hunk 22]
```diff
@@ -3531,7 +4579,14 @@ export function createChecker(program: Program): Checker {
     } else {
       pendingResolutions.start(symId, ResolutionKind.Type);
       type.type = getTypeForNode(prop.value, mapper);
-      type.default = prop.default && checkDefault(prop.default, type.type);
+      if (prop.default) {
+        const defaultValue = checkDefaultValue(prop.default, type.type);
+        if (defaultValue !== null) {
+          type.defaultValue = defaultValue;
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:4585]: Broken scneario

```
const b = 1;
const c: int16 = 1;
model Foo {
   a: int32 = 1;
   b: int32 = b;
   c: int32 = c;
}
```

```
Default a { type: 'int32', scalar: 'int32' }
Default b { type: undefined, scalar: undefined }
Default c { type: 'int16', scalar: 'int16' }
```

File: docs/language-basics/values.md
Comment (timotheeguerin) [inline docs/language-basics/values.md:1]: Should emit error for both those props
```
model A<T extends int32 | valueof int32> {
  prop: typeof T;
  other: T;
}
```

Comment (timotheeguerin) [reply docs/language-basics/values.md:1]: and this case
```
model A<T extends valueof int32> {
  other: T;
}
```

File: packages/spec/src/spec.emu.html [hunk 23]
```diff
@@ -430,8 +444,12 @@ <h1>Syntactic Grammar</h1>
     Identifier TemplateParameterConstraint? TemplateParameterDefault?
 
 TemplateParameterConstraint :
-    `extends` Expression
-    
+    `extends` MixedConstraint
+
+MixedConstraint :
+  Expression
+  ValueOfExpression
```
Comment (timotheeguerin) [inline packages/spec/src/spec.emu.html:451]: Update this to support the union case

File: packages/compiler/src/core/checker.ts [hunk 24]
```diff
@@ -628,10 +684,306 @@ export function createChecker(program: Program): Checker {
...
+    constraint?: CheckValueConstraint,
+    options: { legacyTupleAndModelCast?: boolean } = {}
+  ): Value | null {
+    const initial = checkNode(node, mapper, constraint);
+    if (initial === null) {
+      return null;
+    }
+    let entity: Type | Value | null;
+    if ("metaKind" in initial) {
+      compilerAssert(initial.metaKind === "Indeterminate", "Expected indeterminate entity");
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:736]: not needed?

File: packages/compiler/src/core/checker.ts [hunk 25]
```diff
@@ -2988,6 +3665,496 @@ export function createChecker(program: Program): Checker {
...
+          format: { typeKind: target.kind },
+          target: node.target,
+        })
+      );
+      return null;
+    }
+  }
+
+  function checkTypeOfExpression(node: TypeOfExpressionNode, mapper: TypeMapper | undefined): Type {
+    const entity = checkNode(node.target, mapper, undefined);
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:4120]: can just call getTypeForNode?

File: packages/compiler/src/core/checker.ts [hunk 26]
```diff
@@ -3679,7 +4869,6 @@ export function createChecker(program: Program): Checker {
 
     const symbolLinks = getSymbolLinks(sym);
 
-    let args = checkDecoratorArguments(decNode, mapper);
     let hasError = false;
     if (symbolLinks.declaredType === undefined) {
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:4873]: broken

namespace A {
  const a = 1;
}

File: packages/compiler/src/core/checker.ts (hunk 25 above)
Comment (timotheeguerin) [reply packages/compiler/src/core/checker.ts:4120]: this doesn't work we wnat to get the type of a value not just figure out if indeterminate should be a type

File: docs/language-basics/values.md [hunk 27]
```diff
@@ -0,0 +1,125 @@
...
+```typespec
+const points = #[#{ x: 0, y: 0 }, #{ x: 1, y: 1 }];
+```
+
+As with object values, array values cannot contain types.
+
+If an array type defines a minimum and maximum size using the `@minValue` and `@maxValue` decorators, the compiler will validate that the array value has the appropriate number of items. For example:
+
+```typespec
+/** Can have at most 3 tags */
```
Comment (markcowl) [inline docs/language-basics/values.md:43]:
```suggestion
/** Can have at most 2 tags */
```

File: packages/compiler/src/core/parser.ts (hunk 11 above)
Comment (timotheeguerin) [reply packages/compiler/src/core/parser.ts:1116]: That does the same here [playground](https://cadlplayground.z22.web.core.windows.net/prs/3022/?c=c2NhbGFyIG15IHsKICA7Cn0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

File: .chronus/changes/feature-object-literals-2024-3-16-10-38-3.md [hunk 28]
```diff
@@ -0,0 +1,24 @@
+---
+changeKind: deprecation
+packages:
+  - "@typespec/compiler"
+---
+
+Decorator API: Legacy marshalling logic
+
+  If a library had a decorator with `valueof` one of those types `numeric`, `int64`, `uint64`, `integer`, `float`, `decimal`, `decimal128`, `null` it used to marshall those as JS `number` and `NullType` for `null`. With the introduction of values we have a new marshalling logic which will marshall those numeric types as `Numeric` and the others will remain numbers. `null` will also get marshalled as `null`.
```
Comment (bterlson) [inline .chronus/changes/feature-object-literals-2024-3-16-10-38-3.md:9]:
```suggestion
With the introduction of values, the decorator marshalling behavior has changed in some cases. This behavior is opt-in by setting the `valueMarshalling` package flag to `"new"`, but will be the default behavior in future versions. It is strongly recommended to adopt this new behavior as soon as possible.
```

File: .chronus/changes/feature-object-literals-2024-3-16-10-38-3.md [hunk 29]
```diff
@@ -0,0 +1,24 @@
...
+
+  For now this is an opt-in behavior with a warning on decorators not opt-in having a parameter with a constraint from the list above.
```
Comment (bterlson) [inline .chronus/changes/feature-object-literals-2024-3-16-10-38-3.md:11]:
```suggestion
```

File: .chronus/changes/feature-object-literals-2024-2-15-18-36-3.md [hunk 30]
```diff
@@ -0,0 +1,30 @@
+---
+# Change versionKind to one of: internal, fix, dependencies, feature, deprecation, breaking
+changeKind: feature
+packages:
+  - "@typespec/compiler"
+---
+
+Values In TypeSpec [See docs](https://tspwebsitepr.z22.web.core.windows.net/prs/3022/docs/next/language-basics/values)
```
[the remark this answers is not in the document]
Comment (timotheeguerin) [reply .chronus/changes/feature-object-literals-2024-2-15-18-36-3.md:8]: yep good catch,  meant to do that

**Review by bterlson — COMMENTED** [review]
Still need to review checker.

File: packages/json-schema/lib/main.tsp [hunk 31]
```diff
@@ -35,6 +35,7 @@ extern dec id(target: unknown, id: valueof string);
  *
  * @param value The numeric type must be a multiple of this value.
  */
+#suppress "deprecated" ""
```
[the remark this answers is not in the document]
Comment (timotheeguerin) [reply packages/json-schema/lib/main.tsp:38]: no probably forgot to remove when testing

[the remark this answers is not in the document]
Comment (timotheeguerin) [reply packages/json-schema/lib/main.tsp:38]: actually emits the warning if I remove

File: packages/compiler/src/core/types.ts [hunk 32]
```diff
@@ -1783,23 +1992,29 @@ export type LocationContext =
 
 /** Defined in the user project. */
 export interface ProjectLocationContext {
-  type: "project";
+  readonly type: "project";
+  readonly flags?: ModuleFlags;
```
[the remark this answers is not in the document]
Comment (timotheeguerin) [reply packages/compiler/src/core/types.ts:1996]: ah only renamed the function

File: packages/compiler/src/core/types.ts [hunk 33]
```diff
@@ -295,17 +338,85 @@ export interface ModelProperty extends BaseType, DecoratedType {
...
+  | StringValue
+  | BooleanValue
+  | ObjectValue
+  | ArrayValue
+  | EnumValue
+  | NullValue;
+
+interface BaseValue {
+  valueKind: string;
+  type: Type; // Every value has a type. That type could be something completely different(much wider type)
```
[the remark this answers is not in the document]
Comment (timotheeguerin) [reply packages/compiler/src/core/types.ts:368]: Think that was a copy paste from the design meeting proposal, updating

File: packages/compiler/src/core/checker.ts [hunk 34]
```diff
@@ -1466,18 +1985,59 @@ export function createChecker(program: Program): Checker {
...
 
+  function checkDecoratorLegacyMarshalling(decorator: Decorator) {
+    const marshalling = resolveDecoratorArgMarshalling(decorator);
+    function reportDeprecatedLegacyMarshalling(param: MixedFunctionParameter, message: string) {
+      reportDeprecated(
+        program,
+        [
+          `Parameter ${param.name} of decorator ${decorator.name} is using legacy marshalling but is accepting ${message}.`,
+          `This will change in the future.`,
+          'To opt-in today add `export const $flags = {decoratorArgMarshalling: "new"}}` to your library.',
```
Comment (bterlson) [inline packages/compiler/src/core/checker.ts:2009]:
```suggestion
          'Add `export const $flags = {decoratorArgMarshalling: "new"}}` to your library to opt-in to the new marshalling behavior.',
```

File: packages/compiler/src/core/checker.ts [hunk 35]
```diff
@@ -3987,6 +5333,58 @@ export function createChecker(program: Program): Checker {
...
+
+  function checkScalarConstructor(
+    node: ScalarConstructorNode,
+    mapper: TypeMapper | undefined,
+    parentScalar: Scalar
+  ): ScalarConstructor {
+    const name = node.id.sv;
+    const links = getSymbolLinksForMember(node);
+    if (links && links.declaredType && mapper === undefined) {
+      // we're not instantiating this union variant and we've already checked it
```
Comment (bterlson) [inline packages/compiler/src/core/checker.ts:5366]:
```suggestion
      // we're not instantiating this scalar constructor and we've already checked it
```

?

File: packages/compiler/src/core/types.ts [hunk 36]
```diff
@@ -143,14 +166,33 @@ export interface Projector {
...
+  /** Type constraints */
+  readonly type?: Type;
+
+  /** Expecting value */
+  readonly valueType?: Type;
+}
+
+/** When an entity that could be used as a type or value has not figured out if it is a value or type yet. */
+export interface IndeterminateEntity {
+  readonly metaKind: "Indeterminate";
```
Comment (bterlson) [inline packages/compiler/src/core/types.ts:187]: I think we want a more descriptive name for this.

**Review by bterlson — APPROVED** [review]

File: packages/compiler/src/core/types.ts [hunk 37]
```diff
@@ -72,44 +87,53 @@ export type TemplatedType = Model | Operation | Interface | Union | Scalar;
 
 export interface TypeMapper {
   partial: boolean;
-  getMappedType(type: TemplateParameter): Type;
-  args: readonly Type[];
-  /** @internal */ map: Map<TemplateParameter, Type>;
+  getMappedType(type: TemplateParameter): Type | Value | IndeterminateEntity;
+  args: readonly (Type | Value | IndeterminateEntity)[];
```
Comment (MaryGao) [inline packages/compiler/src/core/types.ts:91]: @timotheeguerin that's interesting, do we take this change as breaking change?

Our code would fail compile due to this change.

Comment (qiaozha) [reply packages/compiler/src/core/types.ts:91]: widen the union in output is a breaking, in this case that union type is being used by us, it's an output, therefore it's a breaking. as inspired by the point 6 of @xirzec 's summary of what should be considered as breaking https://github.com/Azure/azure-sdk-for-js/issues/22983#issuecomment-1230916210
