### PR TITLE
Fix compiler mismatch error recommendation

### LINKED ISSUE #1853: tsp-server not found error gives path to the unix bash file
This error 
```
If this warning occurs in the IDE, try configuring the `tsp-server` path to E:/git/repos/Fiji-Services-EdgeZoneRP6/Fiji-Services-EdgeZoneRP/src/EdgeZoneRpv2/src/typespec/typespec/node_modules/@typespec/compiler/.bin/tsp-server.
```
gives the path you should configure but it points to the bash file and then break on windows. 

Should change to point to the `compiler/` folder

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #1853

### CODE REVIEW

File: packages/compiler/core/program.ts [hunk 1]
```diff
@@ -986,9 +986,7 @@ export async function compile(
     );
 
     if (actual.mainFile !== expected && MANIFEST.version !== actual.manifest.version) {
-      // we have resolved node_modules/@typespec/compiler/dist/core/index.js and we want to get
-      // to the shim executable node_modules/.bin/tsp-server
-      const betterTypeSpecServerPath = resolvePath(actual.path, ".bin/tsp-server");
+      const betterTypeSpecServerPath = actual.path;
```
Comment (daviwil) [inline packages/compiler/core/program.ts:989]: Does this actually improve the error, though?  Seems like it just reverts back to pointing back to the `.js` file instead.  If it does improve things, maybe we can just drop the `betterTypeSpecServerPath` and use `actual.path` instead?

Comment (timotheeguerin) [reply packages/compiler/core/program.ts:989]: The comment above is actually incorrect, it was not updated last times actual.path is pointing to the compiler/ folder

**Review by daviwil — APPROVED** [review]
