### PR TITLE
[emitter-framework] Use Alloy for InterfaceMember

### LINKED ISSUE #6916: [Bug]: Emitter framework needs to adopt alloy InterfaceMember
### Describe the bug

Presently the InterfaceMember component in EF is fully bespoke, so is missing many of the capabilities in the corresponding Alloy component, most notably the ability to give an interface member a refkey.

### Reproduction

.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by maorleger**
## What

Removes bespoke implementation of InterfaceMember in favor of Alloy
Updates test expectation

## Why

Using Alloy here provides a few benefits: proper quoting of member names,
formatting, etc.

Resolves #6916 

## Callouts

Please review carefully as this is my first PR in this space

### CODE REVIEW

File: packages/emitter-framework/src/typescript/components/interface-declaration.tsx [hunk 1]
```diff
@@ -144,10 +131,13 @@ function membersFromType(type: Model | Interface): Children {
...
   return (
-    <ay.For each={Array.from(typeMembers.entries())} line>
-      {([_, prop]) => {
-        return <InterfaceMember type={prop} />;
-      }}
-    </ay.For>
+    <>
+      <ay.For each={Array.from(typeMembers.entries())} line ender=";">
+        {([_, prop]) => {
+          return <InterfaceMember type={prop} />;
```
Comment (maorleger) [inline packages/emitter-framework/src/typescript/components/interface-declaration.tsx:137]: TODO: pass a refkey? What would be an applicable refkey?

File: packages/emitter-framework/src/typescript/components/interface-declaration.tsx [hunk 2]
```diff
@@ -70,13 +60,10 @@ export interface InterfaceExpressionProps extends ts.InterfaceExpressionProps {
 }
 
 export function InterfaceExpression({ type, children }: InterfaceExpressionProps) {
-  const members = type ? membersFromType(type) : [];
```
Comment (maorleger) [inline packages/emitter-framework/src/typescript/components/interface-declaration.tsx:73]: Q: why is the guard here? The type of `type` suggests its always availabe?

File: packages/emitter-framework/src/typescript/components/interface-member.tsx [hunk 3]
```diff
@@ -8,39 +9,50 @@ import { TypeExpression } from "./type-expression.js";
...
     return (
-      <>
-        "{name}"{optionality}: <TypeExpression type={unpackedType} />;
-      </>
+      <ts.InterfaceMember
+        name={name}
+        optional={props.optional === true || props.type.optional === true}
+        type={<TypeExpression type={unpackedType} />}
+        refkey={ay.refkey(props.type)}
+        readonly={Boolean(props.type.decorators?.find((d) => d.decorator.name === "@readonly"))}
```
Comment (timotheeguerin) [inline packages/emitter-framework/src/typescript/components/interface-member.tsx:36]: we don't have this decorator or exact concept in typespec, i think for now can keep things as not readonly

File: packages/emitter-framework/src/typescript/components/interface-declaration.tsx [hunk 4]
```diff
@@ -124,7 +111,7 @@ function getExtendsType(type: Model | Interface): Children | undefined {
   );
 }
 
-function membersFromType(type: Model | Interface): Children {
+function interfaceMembers({ type, children }: TypedInterfaceDeclarationProps) {
```
Comment (timotheeguerin) [inline packages/emitter-framework/src/typescript/components/interface-declaration.tsx:114]: interface body?

File: packages/emitter-framework/src/typescript/components/interface-member.tsx [hunk 5]
```diff
@@ -8,39 +9,50 @@ import { TypeExpression } from "./type-expression.js";
...
       unpackedType = part.type;
     }
 
     return (
-      <>
-        "{name}"{optionality}: <TypeExpression type={unpackedType} />;
-      </>
+      <ts.InterfaceMember
+        name={name}
+        optional={props.optional === true || props.type.optional === true}
```
Comment (timotheeguerin) [inline packages/emitter-framework/src/typescript/components/interface-member.tsx:33]:
```suggestion
        optional={props.optional ?? props.type.optional}
```

File: packages/emitter-framework/src/typescript/components/interface-member.tsx [hunk 6]
```diff
@@ -8,39 +9,50 @@ import { TypeExpression } from "./type-expression.js";
...
+
     return (
-      <>
-        {name}({params}): {returnType};
-      </>
+      <ts.InterfaceMember
+        name={name}
+        type={
+          <>
+            ({params}): {returnType}
```
Comment (timotheeguerin) [inline packages/emitter-framework/src/typescript/components/interface-member.tsx:50]:
```suggestion
            ({params}) => {returnType}
```

I think this might have been incorrect before as well

File: packages/emitter-framework/src/typescript/components/interface-declaration.tsx (hunk 2 above)
Comment (bterlson) [reply packages/emitter-framework/src/typescript/components/interface-declaration.tsx:73]: I don't know...

Comment (timotheeguerin) [reply packages/emitter-framework/src/typescript/components/interface-declaration.tsx:73]: yeah type should always be set according to the definition, proably just a mistake

File: packages/emitter-framework/src/typescript/components/interface-declaration.tsx (hunk 1 above)
Comment (bterlson) [reply packages/emitter-framework/src/typescript/components/interface-declaration.tsx:137]: I don't think we can make one intended for users, which is an interesting limitation of using this component. I think for now if you need to reference the interface members you'll have to use InterfaceMember manually.

File: packages/emitter-framework/src/typescript/components/interface-declaration.tsx (hunk 4 above)
Comment (bterlson) [reply packages/emitter-framework/src/typescript/components/interface-declaration.tsx:114]: This is a component, so capital InterfaceMembers (or InterfaceBody, sure!)

Also, don't destructure props in Alloy. You need to avoid triggering gets on props because getting a prop value that is reactive needs to happen in a reactive scope (in the future, you will get a warning about this), and destructuring destroys the signal so if either type or children change you won't get the updated values.

File: packages/emitter-framework/src/typescript/components/interface-declaration.tsx [hunk 7]
```diff
@@ -144,10 +131,13 @@ function membersFromType(type: Model | Interface): Children {
   }
 
   return (
-    <ay.For each={Array.from(typeMembers.entries())} line>
-      {([_, prop]) => {
-        return <InterfaceMember type={prop} />;
-      }}
-    </ay.For>
+    <>
+      <ay.For each={Array.from(typeMembers.entries())} line ender=";">
```
Comment (bterlson) [inline packages/emitter-framework/src/typescript/components/interface-declaration.tsx:135]: Since you don't need the key, just use `.values()` here.

File: packages/emitter-framework/src/typescript/components/interface-member.tsx (hunk 6 above)
Comment (bterlson) [reply packages/emitter-framework/src/typescript/components/interface-member.tsx:50]: agree

File: packages/emitter-framework/src/typescript/components/interface-member.tsx [hunk 8]
```diff
@@ -8,39 +9,50 @@ import { TypeExpression } from "./type-expression.js";
...
+          </>
+        }
+        refkey={props.refkey ?? ay.refkey(props.type)}
+        readonly={Boolean(props.type.decorators?.find((d) => d.decorator.name === "@readonly"))}
```
Comment (bterlson) [inline packages/emitter-framework/src/typescript/components/interface-member.tsx:54]: another instance of readonly that should be removed.

File: packages/emitter-framework/test/typescript/components/member-expression.test.tsx [hunk 9]
```diff
@@ -36,7 +36,7 @@ describe("Typescript Enum Member Expression", () => {
         three = 3
       }
       interface Bar {
-        "one": Foo.one;
+        one: Foo.one;
```
Comment (bterlson) [inline packages/emitter-framework/test/typescript/components/member-expression.test.tsx:39]: ahhhhhhhhhhhhh yeah that's the stuff

**Review by bterlson — CHANGES_REQUESTED** [review]

File: packages/emitter-framework/src/typescript/components/interface-declaration.tsx (hunk 4 above)
Comment (timotheeguerin) [reply packages/emitter-framework/src/typescript/components/interface-declaration.tsx:114]: its technically not used as a component though, so have to update that as well at point of usage

Comment (maorleger) [reply packages/emitter-framework/src/typescript/components/interface-declaration.tsx:114]: Can do, and yeah it would not be obvious to future me that destructuring has this side-effect of losing reactivity so some sort of linter rule would be helpful 🙏

File: packages/emitter-framework/src/typescript/components/interface-member.tsx (hunk 6 above)
Comment (maorleger) [reply packages/emitter-framework/src/typescript/components/interface-member.tsx:50]: Actually nevermind - I _think_ a test already exists I just have to unskip it 👍 https://github.com/microsoft/typespec/blob/main/packages/emitter-framework/test/typescript/components/interface-declaration.test.tsx#L511-L519

File: packages/emitter-framework/src/typescript/components/interface-declaration.tsx (hunk 4 above)
Comment (bterlson) [reply packages/emitter-framework/src/typescript/components/interface-declaration.tsx:114]: Indeed, an alloy lint rule would be very nice!

Comment (maorleger) [reply packages/emitter-framework/src/typescript/components/interface-declaration.tsx]: Created #6953 to address this in the future. Assigned to me, but I'll try to hold off for a few sprints 😄 

Also address all feedback so far - going to resolve any conversations where I addressed the feedback

File: packages/emitter-framework/test/typescript/components/interface-declaration.test.tsx [hunk 10]
```diff
@@ -674,8 +674,8 @@ describe("Typescript Interface", () => {
         const actualContent = await format(testFile.contents as string, { parser: "typescript" });
         const expectedContent = await format(
           `export interface WidgetOperationsExtended {
-          getName(id: string): Widget;
-          delete(id: string): void;
+          getName: (id: string) => Widget;
+          delete: (id_2: string) => void;
```
Comment (maorleger) [inline packages/emitter-framework/test/typescript/components/interface-declaration.test.tsx:678]: This one is interesting - does not appear related to my PR but this test was also skipped prior to this. Any idea why the _2 is added here or how to address it would be much appreciated - even a "yeah, this is fine" would be helpful

Comment (timotheeguerin) [reply packages/emitter-framework/test/typescript/components/interface-declaration.test.tsx:678]: hhm, this I think is a sign that its a missing a scope boundary.
When you create the params you probably want to warp in a `<Scope/>`  component

File: packages/emitter-framework/test/typescript/components/interface-declaration.test.tsx [hunk 11]
```diff
@@ -337,6 +337,39 @@ describe("Typescript Interface", () => {
         expect(actualContent).toBe(expectedContent);
       });
 
+      it("renders an empty interface", async () => {
```
Comment (bterlson) [inline packages/emitter-framework/test/typescript/components/interface-declaration.test.tsx:340]:
```suggestion
      it("renders an empty interface with a never-typed member", async () => {
```

File: packages/emitter-framework/test/typescript/components/interface-declaration.test.tsx [hunk 12]
```diff
@@ -572,8 +605,8 @@ describe("Typescript Interface", () => {
         const actualContent = await format(testFile.contents as string, { parser: "typescript" });
         const expectedContent = await format(
           `export interface WidgetOperations {
-          getName(foo: Foo): string;
-          getOtherName(name: string): string
+          getName: (foo: Foo) => string;
```
Comment (bterlson) [inline packages/emitter-framework/test/typescript/components/interface-declaration.test.tsx:608]: Quite sad about this actually, but fine for now.

**Review by bterlson — APPROVED** [review]

**Review by timotheeguerin — APPROVED** [review]
