### PR TITLE
`tsp format` should return non-zero exit code on failures

### LINKED ISSUE #2323: tsp format doesn't return 1 when it fails to format
when I run 
`npx tsp format xxx.tsp`
where it prints out 
`File xxx.tsp failed to fromat. `
to standard error (also typo on the error message fromat instead of format). This should probably return 1 since the tool failed to format the tsp file. However, the return code was 0

### PR DESCRIPTION
**Pull request by daviwil**
This PR fixes #2323 by returning a non-zero exit code upon any failure when `tsp format` is executed at the command line.  I'm also changing the return type of `formatTypeSpecFiles` to return a list of file paths that failed, not sure whether that explicitly qualifies as a breaking change.  If needed, I can create a new function to expose and wrap it with the original function without changing its signature.

### CODE REVIEW

File: packages/compiler/src/core/formatter-fs.ts [hunk 1]
```diff
@@ -13,12 +13,14 @@ export interface TypeSpecFormatOptions {
 /**
  * Format all the TypeSpec files.
  * @param patterns List of wildcard pattern searching for TypeSpec files.
+ * @returns list of files which failed to format.
  */
 export async function formatTypeSpecFiles(
```
Comment (timotheeguerin) [inline packages/compiler/src/core/formatter-fs.ts:18]: A more consistent api with others would be to return a list of diagnostics. And maybe don't log the error in the formatTypeSpecFiles and let the consumer to log the diagnostics

Comment (daviwil) [reply packages/compiler/src/core/formatter-fs.ts:18]: Fair point, I'll give that a shot.  What do you think about changing the return type signature of this existing function?  Should I create a separate function for this new behavior?

Comment (timotheeguerin) [reply packages/compiler/src/core/formatter-fs.ts:18]: It goes from void to returning something so I shouldn't be a breaking change. I think it is fine to return `Promise<readonly Diagnostic[]>` or just a boolean showing the success. Just feels like returning a list of files might be confusing that it could be the list of formatted files.

Which actually maybe we should do that:

```ts
interface FormattingResult {
  formattedFiles: string[]
}
export async function formatTypeSpecFiles(): [FormattingResult, readonly Diagnostic[]]

// Or just take a list of `string[]` just depends if we see more data being returned in the future I think.
export async function formatTypeSpecFiles(): [string[], readonly Diagnostic[]]
```

Comment (daviwil) [reply packages/compiler/src/core/formatter-fs.ts:18]: Yeah, I'd prefer to have a result object for future use.  Thanks!

Comment (daviwil) [reply packages/compiler/src/core/formatter-fs.ts:24]: Pushed a fix for this, let me know what you think!

File: packages/compiler/src/core/formatter-fs.ts [hunk 2]
```diff
@@ -3,35 +3,52 @@ import { globby } from "globby";
...
+import { createDiagnostic } from "./messages.js";
 import { normalizePath } from "./path-utils.js";
 
 export interface TypeSpecFormatOptions {
   exclude?: string[];
   debug?: boolean;
 }
 
+export interface TypeSpecFormatResult {
+  formattedFiles: string[];
```
Comment (timotheeguerin) [inline packages/compiler/src/core/formatter-fs.ts:16]: can you just add a doc commnent saying this is the path to the formatted files and if it is absolute or relative to the pattern asked. Feel like its something always missing on docs and you have to run the funciton once to know.

**Review by timotheeguerin — APPROVED** [review]
Perfect, just a minor comment to doc the new interface

File: packages/compiler/src/core/formatter-fs.ts (hunk 2 above)
Comment (daviwil) [reply packages/compiler/src/core/formatter-fs.ts:16]: Will do
