### PR TITLE
[compiler] Add typekit support to check if a type is in a namespace

### LINKED ISSUE #7036: [typekit] type.inNamespace(type: Type)
### Describe the bug

Emitter authors often want to know whether a type is in a particular namespace. This api would walk namespace parents to see if the given type is under it.

### Reproduction

*

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by maorleger**
This pull request introduces a new feature to the `@typespec/compiler` package, adding support for checking namespace membership using a new `inNamespace` method. The changes include updates to the core type system, implementation of the feature, and extensive test coverage to ensure correctness.

Added a new `inNamespace` method to the `Type` TypeKit to determine if a type belongs to a specific namespace. This method handles various type scenarios, including models, enums, unions, and operations. (`packages/compiler/src/experimental/typekit/kits/type.ts`, [[1]](diffhunk://#diff-aaa7a0cba000f6acff7c2734746e5f87fcfd7676ee6ff0b49bbe11385194f854R124-R125) [[2]](diffhunk://#diff-aaa7a0cba000f6acff7c2734746e5f87fcfd7676ee6ff0b49bbe11385194f854R277-R313)

Resolves #7036

### CODE REVIEW

File: packages/compiler/src/experimental/typekit/kits/type.ts [hunk 1]
```diff
@@ -272,5 +274,39 @@ defineKit<TypekitExtension>({
     isUserDefined(type) {
       return getLocationContext(this.program, type).type === "project";
     },
+    inNamespace(type: Type, namespace: Namespace): boolean {
```
Comment (maorleger) [inline packages/compiler/src/experimental/typekit/kits/type.ts:277]: TODO: allowing type or namespace to be optional would simplify this code a bunch - would it also provide a more flexible API for users? Should we allow that and just return false if either is undefined?

File: packages/compiler/src/experimental/typekit/kits/type.ts [hunk 2]
```diff
@@ -272,5 +274,39 @@ defineKit<TypekitExtension>({
...
+      if (type === namespace) {
+        return true;
+      }
+
+      // Handle types that can be sourced from other types
+      if (type.kind === "ModelProperty") {
```
Comment (maorleger) [inline packages/compiler/src/experimental/typekit/kits/type.ts:283]: Definitely going to split up this ternary - I know it's hard to read (at least for me!)

File: packages/compiler/src/experimental/typekit/kits/type.ts [hunk 3]
```diff
@@ -272,5 +274,39 @@ defineKit<TypekitExtension>({
...
+      // Handle members of container types
+      if (type.kind === "EnumMember") {
+        return this.type.inNamespace(type.enum, namespace);
+      }
+      if (type.kind === "UnionVariant") {
+        return this.type.inNamespace(type.union, namespace);
+      }
+
+      // Handle namespace-containing types
+      if (type.kind === "Operation" && type.interface) {
```
Comment (timotheeguerin) [inline packages/compiler/src/experimental/typekit/kits/type.ts:300]: operation also can have a namespace

File: packages/compiler/src/experimental/typekit/kits/type.ts (hunk 2 above)
Comment (timotheeguerin) [reply packages/compiler/src/experimental/typekit/kits/type.ts:283]: I would also change this to just a swtich statement on the `type.kind`

Comment (maorleger) [reply packages/compiler/src/experimental/typekit/kits/type.ts:283]: I was _literally_ just doing that 🤝 😄

File: packages/compiler/src/experimental/typekit/kits/type.ts [hunk 4]
```diff
@@ -272,5 +281,42 @@ defineKit<TypekitExtension>({
...
+
+      // A namespace is always in itself
+      if (type === namespace) {
+        return true;
+      }
+
+      // Handle types with known containers
+      switch (type.kind) {
+        case "ModelProperty":
+          if (type.sourceProperty) {
```
Comment (timotheeguerin) [inline packages/compiler/src/experimental/typekit/kits/type.ts:296]: shouldn't go to sourceProperty as this might go to a different namespace. It links to the prop that was used to consutrct it in a spread or model is

File: packages/compiler/src/experimental/typekit/kits/type.ts [hunk 5]
```diff
@@ -272,5 +281,42 @@ defineKit<TypekitExtension>({
     isUserDefined(type) {
       return getLocationContext(this.program, type).type === "project";
     },
+    inNamespace(type: Type, namespace: Namespace): boolean {
+      compilerAssert(type !== undefined, "parameter 'type' is undefined");
+      compilerAssert(namespace !== undefined, "parameter 'namespace' is undefined");
```
[the remark this answers is not in the document]
Comment (maorleger) [reply packages/compiler/src/experimental/typekit/kits/type.ts:286]: Yeah, I don't know - I just hate seeing errors like `Uncaught TypeError: Cannot read properties of undefined (reading 'kind')` - it tells me nothing (like whether type or namespace was undefined). I am happy to remove it if you want

[the remark this answers is not in the document]
Comment (maorleger) [reply packages/compiler/src/experimental/typekit/kits/type.ts]: Sounds good! I removed it

File: packages/compiler/src/experimental/typekit/kits/type.ts (hunk 4 above)
Comment (maorleger) [reply packages/compiler/src/experimental/typekit/kits/type.ts]: Ah, got it. Fixed!

**Review by timotheeguerin — APPROVED** [review]
