### PR TITLE
Provide an operation id resolver

### LINKED ISSUE #3080: OpenAPI3 Emitter could provide a way to configure operationId
### Clear and concise description of the problem

Currently we always generate an operationId which is what we would want for azure services but from [this discussion](https://github.com/microsoft/typespec/discussions/3076) some existing use case might involve not including the operationId and resorting to the next tool auto resolving names. Forcing the names like that break those flows.

We could add an emitter option: `operation-id-resolution` with the following option:
- `auto` current behavior, resolve automatically or use explicit `@operationId` if provided
- `explicit-only` do not generate one only include if there is `@operationId`
- `omit` never include(not sure we need this option)

Example:
```yaml
options: 
   @typespec/openapi3:
     operation-id-resolution: auto
```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### LINKED ISSUE #8511: [Bug]: openapi same name inner namespaces results in duplicate operationId
### Describe the bug

When declaring operations in namespaces in hierarchies and having same namespace names, because openapi-emitter uses only one immediate parent namespace or interface, this results in underspecified operationId's generated in final OAS document.

I think for explicit operationId resolution, OAS emitter should see full namespaces chain and resolve whole path.

### Reproduction

https://typespec.io/playground/?options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D&e=%40typespec%2Fopenapi3&vs=%7B%7D&c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBIdHRwOwoKQHNlcnZpY2UoI3sgdGl0bGU6ICJTxhMiIH0pCm5hbWVzcGFjZSBPdXRlciB7CiAgb3AgdGVzdCgpOiB2b2lkOwoKICBAcm91dGUoImlubmVyIikKICDKOknEFMU61jzUPthA00LEFX0KxAR9Cgo%3D

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #8511 (Resolve duplicate operationId)
fix #3080 (Provide a way to configure Operation id)

### CODE REVIEW

File: packages/openapi3/src/lib.ts [hunk 1]
```diff
@@ -91,8 +91,20 @@ export interface OpenAPI3EmitterOptions {
...
+
+  /**
+   * How should operation ID be generated when `@operationId` is not used.
+   * Available options are
+   * - `parent-underscore`: Uses the parent namespace/interface and operation name to generate the ID.
+   * - `fqn`: Uses the fully qualified name(from service root) of the operation to generate the ID.
+   * - `none`: Do not generate operation ids.
+   * @default parent-underscore
+   */
+  "operation-id-strategy"?: OperationIdStrategy;
```
Comment (timotheeguerin) [inline packages/openapi3/src/lib.ts]: Question here on the names if people have opinions. Could be
- `operation-id-resolution`
- `operation-id`

File: packages/openapi3/src/lib.ts [hunk 2]
```diff
@@ -91,8 +91,20 @@ export interface OpenAPI3EmitterOptions {
...
 }
 
+export type OperationIdStrategy = "parent-underscore" | "fqn" | "none";
```
Comment (timotheeguerin) [inline packages/openapi3/src/lib.ts]: Question on the options here too 
- `container-underscore`
- `fqn-dot`
- `explicit-only`

File: packages/openapi3/src/operation-id-resolver/operation-id-resolver.ts [hunk 3]
```diff
@@ -0,0 +1,82 @@
+import { isGlobalNamespace, isService, type Operation, type Program } from "@typespec/compiler";
+import { getOperationId } from "@typespec/openapi";
+import { OperationIdStrategy } from "../lib.js";
+
+export class OperationIdResolver {
```
Comment (witemple-msft) [inline packages/openapi3/src/operation-id-resolver/operation-id-resolver.ts:9]: This is a nice abstraction. If we ever want to expose this functionality programmatically it will be beneficial to depend on an interface instead of a concrete implementation, e.g. `interface OperationIdResolver { resolve(op: Operation): string | undefined; }`, and `class OperationIdResolverImpl implements OperationIdResolver`.

File: packages/openapi3/src/lib.ts (hunk 1 above)
Comment (witemple-msft) [reply packages/openapi3/src/lib.ts]: I think `operation-id-strategy` is nice.

File: packages/openapi3/src/lib.ts (hunk 2 above)
Comment (witemple-msft) [reply packages/openapi3/src/lib.ts]: I would prefer `container` to `parent` since we use this terminology somewhat pervasively already in various TypeSpec APIs.

Now that I'm looking at it, I think we might want the two settings that you were describing, one to configure how the operation ID is constructed (`parent-container`, `fully-qualified-name`, `none`) and a second one to say what character should be used to join the segments (`underscore`, `dot`, or you could even just make it accept any string). This would just be more flexible and I can imagine someone seeing the three options and thinking "why can't I have the FQN separated by underscores instead of just the container name" or vice versa.

If `none` means "do not emit operation IDs, _ever_" then I think `none` is good, otherwise if the operation ID will still be emitted when the decorator is explicitly used, I think we probably do need something like `explicit-only` instead of `none`.

File: packages/openapi3/src/operation-id-resolver/operation-id-resolver.ts (hunk 3 above)
Comment (timotheeguerin) [reply packages/openapi3/src/operation-id-resolver/operation-id-resolver.ts:9]: I think I'll leave that to whenever we need as this is not exported or exposed in anyway right now. Feels premature to plan for this

File: packages/openapi3/README.md [hunk 4]
```diff
@@ -134,6 +134,10 @@ Note: This is an experimental feature and may change in future versions.
 See https://spec.openapis.org/oas/v3.0.4.html#style-examples for parameter example serialization rules
 See https://github.com/OAI/OpenAPI-Specification/discussions/4622 for discussion on handling parameter examples.
 
+### `operation-id-strategy`
+
+**Type:** `undefined`
```
Comment (witemple-msft) [inline packages/openapi3/README.md:139]: Note that doc generation for `oneOf` option schemas seems unimplemented here. I don't think we should block the feature on this, but we should at least make sure there's an issue tracking it.

Comment (timotheeguerin) [reply packages/openapi3/README.md:139]: created https://github.com/microsoft/typespec/issues/8651
