### PR TITLE
converter: handle nullable array schemas

### LINKED ISSUE #8155: [Bug]: OpenAPI to TypeSpec conversion of arrays of inline enums lead to invalid TypeSpec
### Describe the bug

Using the conversion tool, inline enums for an array are not converted properly. I'd expected an enum definition, either inline (is that possible in TypeSpec), or as a separate type.

### Reproduction

The following component schema

```yaml
    ChatCompletionModalities:
      type: array
      items:
        type: string
        enum:
          - text
          - audio
```

leads to the following TypeSpec

```TypeSpec
union ChatCompletionModalities {
null,
}
```

Which missing the enum values

tool version 1.3.0

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by witemple-msft**
possibly closes #8155

### CODE REVIEW

File: packages/openapi3/src/cli/actions/convert/generators/generate-model.ts [hunk 1]
```diff
@@ -122,6 +122,12 @@ function generateUnion(union: TypeSpecUnion, context: Context): string {
     const primitiveType = getTypeSpecPrimitiveFromSchema(schema);
     if (primitiveType) {
       definitions.push(`${primitiveType},`);
+    } else if (schema.type === "array") {
```
Comment (baywet) [inline packages/openapi3/src/cli/actions/convert/generators/generate-model.ts]:
```suggestion
    } else if (schema.type === "array" || schema.items) {
```

since setting the array type is not technically required by the specification

File: packages/openapi3/test/tsp-openapi3/data-types.test.ts [hunk 2]
```diff
@@ -275,6 +275,35 @@ describe("converts top-level schemas", () => {
...
+        },
+      });
+
+      expect(serviceNamespace.unions.size).toBe(1);
+
+      /* union ChatCompletionModalities { ("text" | "audio")[], null, } */
+      const modalitiesUnion = serviceNamespace.unions.get("ChatCompletionModalities");
+      expect(modalitiesUnion?.decorators.length).toBe(0);
+      const modalitiesUnionVariants = [...(modalitiesUnion?.variants.values() ?? [])];
+      expect(modalitiesUnionVariants.length).toBe(2);
```
Comment (chrisradek) [inline packages/openapi3/test/tsp-openapi3/data-types.test.ts:299]: Coming from alloy tests, these are painful 😢

**Review by chrisradek — APPROVED** [review]
