### PR TITLE
Fix vscode telemetry

### LINKED ISSUE #6618: [Bug]: vscode telemetry broken with latest telemetry library
### Describe the bug

telemetry error reported after the vscode telemetry library is upgraded to 0.98 in #6595 

Image

### Reproduction

check output log when the extension is started.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by RodgeFu**
- Fixes #6618 
- Improve and add more error telemetry

### CODE REVIEW

File: packages/typespec-vscode/src/telemetry/telemetry-client.ts [hunk 1]
```diff
@@ -42,12 +43,8 @@ export class TelemetryClient {
       );
       this._client = undefined;
     } else {
-      this._client = new (TelemetryReporter as any)(
-        `${pkgJson.publisher}.${pkgJson.name}`,
```
Comment (timotheeguerin) [inline packages/typespec-vscode/src/telemetry/telemetry-client.ts:46]: are those info not pass in any other way now?

Comment (RodgeFu) [reply packages/typespec-vscode/src/telemetry/telemetry-client.ts:46]: the latest vscode telemetry will collect these inforamtion automatically, so dont need to pass them explicitly.thx

File: packages/typespec-vscode/src/telemetry/telemetry-client.ts [hunk 2]
```diff
@@ -42,12 +43,8 @@ export class TelemetryClient {
...
-        pkgJson.version,
-        key,
-        true /*first party*/,
-      );
+      // has to convert the TelemetryReporter to any, otherwise it will report error: This expression is not constructable.
```
[the remark this answers is not in the document]
Comment (RodgeFu) [reply packages/typespec-vscode/src/telemetry/telemetry-client.ts:46]: yeah, we need to fix it somehow to avoid unexpected broken next time. thanks.
