### PR TITLE
Fix loading of playground older versions

### LINKED ISSUE #3439: Website should resolve playground libraries from the configured importmap
Problem is right now those are defined in `https://github.com/microsoft/typespec/blob/5698be15fe5968ddb58faac5d34a273b35cef679/packages/playground-website/src/index.ts#L5` and shared for the website playgorund and `next` standalone one. If you add a new library to the standalone one it will require it to be immediately available in the website as well and risk forgetting to add it to the bundle script.

This also breaks loading older versions which didn't have this library.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #3439

### CODE REVIEW

File: website/src/components/playground-component/import-map.ts [hunk 1]
```diff
@@ -26,11 +35,10 @@ export async function loadImportMap({ latestVersion }: { latestVersion: string }
 
   (window as any).importShim.addImportMap(importMap);
 
-  await new Promise((resolve) => setTimeout(resolve, 1000));
```
Comment (timotheeguerin) [inline website/src/components/playground-component/import-map.ts:29]: this feels like it was added for testing and never removed but, will double check with the published version there is no timing issues

Comment (timotheeguerin) [reply website/src/components/playground-component/import-map.ts:29]: seems to work fine

**Review by markcowl — APPROVED** [review]
