### PR TITLE
fix/discriminator invalid symbol

### LINKED ISSUE #8216: [Bug] OpenAPI import leads to invalid symbols when discriminator mappings contain invalid characters
When importing from an OpenAPI description, the following OAS results in the invalid following TypeSpec
 
 ```YAML
 components:
   schemas:
     CreateSpeechResponseStreamEvent:
       anyOf:
         - $ref: '#/components/schemas/SpeechAudioDeltaEvent'
         - $ref: '#/components/schemas/SpeechAudioDoneEvent'
       discriminator:
         propertyName: type
     SpeechAudioDeltaEvent:
       type: object
       properties:
         type:
           type: string
           enum:
             - speech.audio.delta
         audio:
           type: string
     SpeechAudioDoneEvent:
       type: object
       properties:
         type:
           type: string
           enum:
             - speech.audio.done
 ```
 
 
 ```TypeSpec
 @discriminated(#{ envelope: "none", discriminatorPropertyName: "type" })
 union CreateSpeechResponseStreamEvent {
 speech.audio.delta: SpeechAudioDeltaEvent
 speech.audio.done: SpeechAudioDoneEvent
 }
 ```
 
 (notice the symbols for the discriminator are invalid and cause a compilation issue) 

 _Originally posted by @baywet in [#7857](https://github.com/microsoft/typespec/issues/7857#issuecomment-3192465243)_

### PR DESCRIPTION
**Pull request by baywet**
fixes #8216

### CODE REVIEW

File: packages/openapi3/src/cli/actions/convert/generators/generate-model.ts [hunk 1]
```diff
@@ -99,7 +100,9 @@ function generateUnion(union: TypeSpecUnion, context: Context): string {
 
     const value = (memberSchema.properties?.[union.schema.discriminator.propertyName] as any)
       ?.enum?.[0];
-    return value ? `${value}: ` : "";
+    // checking whether the value is using an invalid character as an identifier
+    const valueIdentifier = printIdentifier(value, "disallow-reserved");
```
Comment (baywet) [inline packages/openapi3/src/cli/actions/convert/generators/generate-model.ts]:
```suggestion
    const valueIdentifier = value ? printIdentifier(value, "disallow-reserved") : "";
```
