### PR TITLE
Fix relative file resolution in redirected init template

### LINKED ISSUE #1937: tsp init <url> does not resolve HTTP redirects to new host (e.g. aka.ms)
tsp init <url> can retrieve the file from the aka.ms link through the redirect.

relative path in the scaffolding template are still based on the link shortener rather than the resolved host.

e.g. 

`https://aka.ms/typespec-msgraph/init` resolves to the template file and other files points to aka.ms links.

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #1937

### CODE REVIEW

**Comment by nguerrera** [comment]
Manual testing:

https://aka.ms/nicholg-test-tsp-init -> https://gist.github.com/nguerrera/f6bfbbf0213458827a28024c093c03ba

File: packages/compiler/init/init.ts [hunk 1]
```diff
@@ -65,6 +65,13 @@ interface ScaffoldingConfig extends InitTemplate {
   normalizePackageName: () => (text: string, render: any) => string;
 }
 
+interface TemplatesUrl {
+  /** The original URL specified by the user. */
+  url: string;
+  /** The final URL after HTTP redirects. Populated when template is downloaded. */
+  finalUrl?: string;
```
Comment (timotheeguerin) [inline packages/compiler/init/init.ts:72]: is it not something we could figure out ourself instead of requiring it? Is it common to have this pattern?

Comment (nguerrera) [reply packages/compiler/init/init.ts:72]: The code is a little weird because I avoided significant refactoring, but this is figured out as follows: you pass in { url: X } and finalUrl is added to it so you get { url: X, finalUrl: Y }. This is all internal to the init module and the exported API takes url: string and "just works". Nothing new is required from caller.

The one change that has more impact is that the NodeHost will use the url of the response for the SourceFile path on readUrl instead of the url passed in. This is how init figures out there was a redirect, effectively.

**Review by timotheeguerin — APPROVED** [review]
