### PR TITLE
Fix union of custom scalar with `null` creating an `object` with `allOf` reference

### LINKED ISSUE #5156: [Bug]: Nullable Generic Scalar generated as `object`
### Describe the bug

When using a scalar as a generic, the OpenAPI output sometimes is defined as type `object` even though the file is not an object.

Using typespec v0.62.0

## Typespec

```js
scalar ISODate extends string;

alias RangeUnbound = null;

model Range<Inner> {
  from: Inner | RangeUnbound;
  to: Inner | RangeUnbound;
  lowerInclusive: boolean;
  upperInclusive: boolean;
}

model ISODateRange is Range<ISODate> {}
```

## OpenAPI Output

```yml
ISODateRange:
  type: object
  required:
    - from
    - to
    - lowerInclusive
    - upperInclusive
  properties:
    from:
      type: object
      allOf:
        - $ref: '#/components/schemas/ISODate'
      nullable: true
    to:
      type: object
      allOf:
        - $ref: '#/components/schemas/ISODate'
      nullable: true
    lowerInclusive:
      type: boolean
    upperInclusive:
      type: boolean
```

## Expected

```yml
RangeUnbound:
  type: null
ISODateRange:
  type: object
  required:
    - from
    - to
    - lowerInclusive
    - upperInclusive
  properties:
    from:
      oneOf:
        - $ref: '#/components/schemas/ISODate'
        - $ref: '#/components/schemas/RangeUnbound'
    to:
      oneOf:
        - $ref: '#/components/schemas/ISODate'
        - $ref: '#/components/schemas/RangeUnbound'
    lowerInclusive:
      type: boolean
    upperInclusive:
      type: boolean
```

or

```yml
ISODateRange:
  type: object
  required:
    - from
    - to
    - lowerInclusive
    - upperInclusive
  properties:
    from:
      type: string
      nullable: true
    to:
      type: string
      nullable: true
    lowerInclusive:
      type: boolean
    upperInclusive:
      type: boolean
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by wanlwanl**
Fix #5156

### CODE REVIEW

**Comment by wanlwanl** [comment]
FYI, inline everything: https://github.com/microsoft/typespec/pull/6240

**Review by chrisradek — APPROVED** [review]

File: packages/openapi3/src/schema-emitter-3-0.ts [hunk 1]
```diff
@@ -206,12 +207,19 @@ export class OpenAPI3SchemaEmitter extends OpenAPI3SchemaEmitterBase<OpenAPI3Sch
...
         ) {
-          if (type && (type.kind === "Model" || type.kind === "Scalar")) {
+          if (type && type.kind === "Model") {
             return new ObjectBuilder({
               type: "object",
               allOf: Builders.array([schema]),
               ...additionalProps,
             });
+          } else if (type && type.kind === "Scalar") {
+            const stdName = $.scalar.getStdBase(type)?.name;
```
Comment (timotheeguerin) [inline packages/openapi3/src/schema-emitter-3-0.ts:217]: I think this will break for anything else but string

Comment (timotheeguerin) [reply packages/openapi3/src/schema-emitter-3-0.ts:217]: [Example playground](https://cadlplayground.z22.web.core.windows.net/prs/6506/?c=bW9kZWwgRm9vIHsKICBpMzI6xAUgfCBudWxsOwp9CgoKc2NhbGFyxRdleHRlbmRzIGludDMyOw%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

Call `getSchemaForStdScalars` after getting the base to get the type + format

File: packages/openapi3/src/schema-emitter-3-0.ts [hunk 2]
```diff
@@ -206,12 +208,28 @@ export class OpenAPI3SchemaEmitter extends OpenAPI3SchemaEmitterBase<OpenAPI3Sch
...
             return new ObjectBuilder({
               type: "object",
               allOf: Builders.array([schema]),
               ...additionalProps,
             });
+          } else if (type && type.kind === "Scalar") {
+            const stdType = $.scalar.getStdBase(type);
+            let outputType: JsonType | undefined = undefined;
+            if (stdType !== null) {
+              const scalarEx = {
```
Comment (timotheeguerin) [inline packages/openapi3/src/schema-emitter-3-0.ts:221]: Sa why do you need to do that ?

Comment (wanlwanl) [reply packages/openapi3/src/schema-emitter-3-0.ts:221]: Since `getSchemaForStdScalars(scalar: Scalar & { name: IntrinsicScalarName }): Schema`, otherwise I need to convert to any `as any`?

Comment (timotheeguerin) [reply packages/openapi3/src/schema-emitter-3-0.ts:221]: Yeah just as any, if you cheating the system already don't need to create another spread. Can also get rid of the if and use ?.

Comment (wanlwanl) [reply packages/openapi3/src/schema-emitter-3-0.ts]: updated

File: packages/openapi3/test/union-schema.test.ts [hunk 3]
```diff
@@ -525,6 +525,51 @@ worksFor(["3.0.0"], ({ diagnoseOpenApiFor, oapiForModel, openApiFor }) => {
...
+      `);
+        deepStrictEqual(openApi.components.schemas.A.properties, {
+          x: {
+            type: expectedType,
+            allOf: [{ $ref: "#/components/schemas/StdScalar" }],
+            nullable: true,
+          },
+        });
+      },
+    );
```
Comment (timotheeguerin) [inline packages/openapi3/test/union-schema.test.ts:571]:
```suggestion
    describe("scalar type property that extends std scalar should always be set as corresponding JSON type when nullable property is present", () => {
    it.each([
      ["bytes", "string"],
      ["numeric", "number"],
      ["integer", "integer"],
      ["int8", "integer"],
      ["int16", "integer"],
      ["int32", "integer"],
      ["int64", "integer"],
      ["safeint", "integer"],
      ["uint8", "integer"],
      ["uint16", "integer"],
      ["uint32", "integer"],
      ["uint64", "integer"],
      ["float", "number"],
      ["float32", "number"],
      ["float64", "number"],
      ["decimal", "number"],
      ["decimal128", "number"],
      ["string", "string"],
      ["boolean", "boolean"],
      ["plainDate", "string"],
      ["utcDateTime", "string"],
      ["offsetDateTime", "string"],
      ["plainTime", "string"],
      ["duration", "string"],
      ["url", "string"],
    ])(
      "%s",
      async (scalarDeclaration: string, expectedType: string) => {
        const openApi = await openApiFor(`
      scalar StdScalar extends ${scalarDeclaration};
      model A {
        x: StdScalar | null;
      }
      `);
        deepStrictEqual(openApi.components.schemas.A.properties.type, expectedType);
      },
    );
  });
```

Comment (timotheeguerin) [reply packages/openapi3/test/union-schema.test.ts:571]: this way all the test show up with different names and under the category + actually only test what the test describe instead of having snapshot tests

**Review by timotheeguerin — APPROVED** [review]
