### PR TITLE
[compiler] $.type.isError returns true for error models

### LINKED ISSUE #6939: [Bug]: TypeKit $.type.isError doesn't check for error decorator
### Describe the bug

The $.type.isError typekit documentation claims it checks for the @error decorator, which would be useful, but it unfortunately just checks if the type is the built-in error type (which should be exposed via built-ins).

### Reproduction

$.type.isError

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by maorleger**
`$.type.isError` should return true for error models (models decorated with `@error`), but not for built-in errors.

Fixes #6939

### CODE REVIEW

File: packages/compiler/src/experimental/typekit/kits/type.ts [hunk 1]
```diff
@@ -214,7 +214,7 @@ defineKit<TypekitExtension>({
       return clone;
     },
     isError(type) {
-      return isErrorType(type);
+      return isErrorType(type) || isErrorModel(this.program, type);
```
Comment (timotheeguerin) [inline packages/compiler/src/experimental/typekit/kits/type.ts:217]: I kinda feel like it should never have been `isErrorType`.

This is not a type you would receive in your emitter or decorator unless there is a bug

Comment (timotheeguerin) [reply packages/compiler/src/experimental/typekit/kits/type.ts:217]: the doc of the typekit also just says it returns true for model with `@error`

Comment (timotheeguerin) [reply packages/compiler/src/experimental/typekit/kits/type.ts:217]: which on a side note should escape the `@error` in backtick or it will be treated as a jsdoc tag

Comment (maorleger) [reply packages/compiler/src/experimental/typekit/kits/type.ts:217]: Gotcha, so you're saying that we should not be checking isErrorType at all, _only_ isErrorModel? 

The issue is not very descriptive so I had to read between the lines a bit. It says "The $.type.isError typekit documentation claims it checks for the https://github.com/error decorator, which would be useful, but it unfortunately **just** checks if the type is the built-in error type (which should be exposed via built-ins)."

So it's a bit hard to tell _what_ exactly is the bug. Are you saying that the correct implementation would just be `return isErrorModel(this.program, type)` ?

Comment (timotheeguerin) [reply packages/compiler/src/experimental/typekit/kits/type.ts:217]: yeah I think so

File: packages/compiler/src/experimental/typekit/kits/type.ts [hunk 2]
```diff
@@ -33,7 +33,7 @@ export interface TypeTypekit {
    */
   finishType(type: Type): void;
   /**
-   * Checks if a type is decorated with @error
+   * Checks if a type is decorated with \@error
```
Comment (timotheeguerin) [inline packages/compiler/src/experimental/typekit/kits/type.ts:36]:
```suggestion
   * Checks if a type is decorated with `@error`
```

usually just do that

File: packages/compiler/src/experimental/typekit/kits/type.ts [hunk 3]
```diff
@@ -33,7 +33,7 @@ export interface TypeTypekit {
...
    * @param type The type to check.
    */
   isError(type: Type): boolean;
```
Comment (timotheeguerin) [inline packages/compiler/src/experimental/typekit/kits/type.ts:39]:
```suggestion
  isError(type: Type) assets type is Model;
```

coudl also maybe do that to get a more precise type

Comment (maorleger) [reply packages/compiler/src/experimental/typekit/kits/type.ts:39]: Yup, although just to clarify I assume we want the typeguard `type is Model` , not the type-assertion (`asserts type is Model`) here right? It should be safe to call with non-error types? Gonna assume yes and resolve but feel free to let me know if you meant something else!

**Review by timotheeguerin — APPROVED** [review]
