### PR TITLE
Fix signature help after comment with no closing parenthesis or angle bracket

### LINKED ISSUE #2012: Signature help: deal with trailing comments in unterminated arg list
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=QGRvYygidGVzdCIsIA%3D%3D)

1. Place cursor here (┆) in decorator without closing paren:
`@doc("test", /*arg*/┆`

2. Press Ctrl+Shift+Space to force signature help

#2000 fixed this for trailing space (common), but not trailing comment (less common). It should handle all trailing trivia. Comments are trickier because the cursor could be mid comment too so we should probably use the comments saved in the AST script node. We might also consider storing all trivia, not just comments, but we can also continue to re-scan whitespace.

I was thinking:

1. add getCommentAtPosition() like getNodeAtPosition() that can do a binary search of the script.comments.
2. add helpers to adjust position forward or backwards over all trivia using (1).

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #2012 

I decided to keep the helpers discussed internal for now at least to just fix the bug. Some bake time wouldn't hurt before committing to them as public API for scenarios outside the language server.

### CODE REVIEW

File: packages/compiler/server/server-utils.ts [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+ * {@link Comment.end}. Unlike {@link getNodeAtPosition}, the end node is
+ * not included since comments can be adjacent to each other with no trivia
+ * or punctuation between them.
+ *
+ * @internal
+ */
+export function getCommentAtPosition(script: TypeSpecScriptNode, pos: number): Comment | undefined {
+  // Comments are ordered by increasing position, use binary search
+  let low = 0;
+  let high = script.comments.length - 1;
```
Comment (timotheeguerin) [inline packages/compiler/server/server-utils.ts:17]: is there any issues to the behavior if we choose not to parse the comments?

Comment (nguerrera) [reply packages/compiler/server/server-utils.ts:17]: Yes, it will break. Good point. Maybe this should throw. It's only in server-utils now so not a problem, but I could see this becoming useful elsewhere and going public. So I'll put in a throw now.

Comment (nguerrera) [reply packages/compiler/server/server-utils.ts:17]: Done.

**Review by timotheeguerin — APPROVED** [review]
