### PR TITLE
Document member ordering and fix projection rename reordering

### LINKED ISSUE #948: Are properties within a model ordered?
In particular, if I spread a model into a parameter list, is the order in which the properties appear well defined? 

If properties of a model are ordered, what is the order of parent vs child properties when `foo extends bar`?

### LINKED ISSUE #970: `renameProperty`, `renameMember` lose order in projection
For this to be true #948, we need to resolve the bug where a property that gets renamed gets moved to the end of the property list/map(Because it is removed then added)

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #970 
Fix #948 

Builds on @timotheeguerin's draft from #981. I renamed the type to `RekeyableMap` from `OrderedMap` since it was noted that "ordered" was confusing on the draft since Map is ordered. I also changed `updateKey` method to `rekey` to match.

Although the observations about perf on #981 remain if you micro-benchmark, I spent some time trying a variety of different approaches that were either just as slow, or very invasive and not meaningfully faster. It does not appear to show up on genuine compilation scenarios end-to-end.

### CODE REVIEW

File: packages/compiler/core/util.ts [hunk 1]
```diff
@@ -492,3 +493,101 @@ export class DuplicateTracker<K, V> {
     }
   }
 }
+
+export function createRekeyableMap<K, V>(entries?: [K, V][]): RekeyableMap<K, V> {
```
Comment (timotheeguerin) [inline packages/compiler/core/util.ts:497]: I guess I am never sure on when and why we do `create` function vs `class` but here wouldn't it make more sense to align with `Map`?

Comment (nguerrera) [reply packages/compiler/core/util.ts:497]: I had trouble exporting class from this file with interface in types. Map is both an interface and a type and I would like to keep types.ts more self-contained and mostly interfaces. I assume there is a way to satisfy the compiler. If you know what I'm missing, happy to change this.

Comment (timotheeguerin) [reply packages/compiler/core/util.ts:497]: ah I see, yeah I guess that's maybe better this way, you can cheat by having both the same name but then if its in different file it can be trouble

**Review by timotheeguerin — APPROVED** [review]
