### PR TITLE
fix error when previewing openapi3.1

### LINKED ISSUE #6359: [Bug]: Error reported when opening operation in the typespec preview (openapi 3.1.0) in vscode
### Describe the bug

Below errors reported when preview typespec with openapi-version 3.1.0. Should be related to the swagger-ui issue https://github.com/swagger-api/swagger-ui/issues/9304 

Image

### Reproduction

Create a Generic Rest project by ```tsp init``` or "Create TypeSpec Project" in vscode
Right click on main.tsp and choose "Show OpenAPI3 Document"
Expand some operation

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by archerzz**
- use `url` property when initializing swagger UI
- update logic to use the file path to open api output file when loading web view
- add tmp folder into web view panel local resource roots
- hide url link under the title of swagger UI

fix #6359

### CODE REVIEW

File: packages/typespec-vscode/src/utils.ts [hunk 1]
```diff
@@ -31,9 +30,9 @@ export async function isDirectory(path: string) {
   }
 }
 
-export async function createTempDir(): Promise<string | undefined> {
+export async function createTempDir(tmpRoot: string): Promise<string | undefined> {
```
Comment (RodgeFu) [inline packages/typespec-vscode/src/utils.ts:33]: suggest changing to createTempDir(tmpRoot: string, prefix: string) to keep the utility function for general purpose instead of just for openapi3-preview.

**Review by timotheeguerin — APPROVED** [review]

File: packages/typespec-vscode/src/utils.ts (hunk 1 above)
Comment (archerzz) [reply packages/typespec-vscode/src/utils.ts]: updated according to comment
