### PR TITLE
Http filtering create in a realm

### LINKED ISSUE #6202: Similar regression to #5999
There's something about the interaction of `@typespec/http` and `@typespec/versioning` that's causing an error with the openapi3 emitter. the json-schema emitter doesn't exhibit the same problem.

[Playground Link](https://typespec.io/playground/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZdmVyc2lvbmluZyI7Cgp1c2luZyBUeXBlU3BlYy5WyR070BtIdHRwOwoKQMdAZWQoxy1zKQpAc2VydmljZQpuYW1lc3BhY2UgRm9vIHsKICBtb2RlbCBCxQwgIEBleGFtcGxlKEMuWCnFEmZpZWxkOiBDOwogIH0KCiAgZW51bSBDxzBYyBbGR0HHFy8vIFRoaXMgY29tYmluYXRpb24gc2VlbXMgdG8gY2F1c2UgdGhlIHByb2JsZW0uxTQuLi5Pa1Jlc3BvbnNlxG7FE0LJeGludGVyZuQAu0RlbVNldHRpbmdzx3BnZXQoKTogQe4ApegBAMcldjFfMF81OiAiMS4wLjUiLMUsfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #6202

### CODE REVIEW

File: packages/compiler/src/core/checker.ts [hunk 1]
```diff
@@ -7182,25 +7183,25 @@ export function filterModelProperties(
     return model;
   }
 
-  const properties = createRekeyableMap<string, ModelProperty>();
-  const newModel: Model = program.checker.createType({
-    kind: "Model",
-    node: undefined,
+  const realm = unsafe_Realm.realmForType.get(model);
```
Comment (timotheeguerin) [inline packages/compiler/src/core/checker.ts:7186]: shouldn't need to use the unsafe version here

**Review by markcowl — APPROVED** [review]
