### PR TITLE
Fix signature help with trailing space in unterminated arg list

### LINKED ISSUE #1990: Signature help does not work with space after delimiter and no closing paren
Type space after last delimiter with no closing paren: `@doc("", ┇`

Or press Ctrl+Shift+Space to force signature help with cursor at that position marked with `┇`.

https://cadlplayground.z22.web.core.windows.net/?c=DQpAZG9jKCIiLCANCm1vZGVsIE0gew0KDQp9

Follow up to #1983. This already didn't work for decorators, but is mitigated by IDE inserting closing paren for you when you type open paren and you don't get the same mitigation with automatic `>` insertion for template instantiation.

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #1990

### CODE REVIEW

File: packages/compiler/core/parser.ts [hunk 1]
```diff
@@ -3088,6 +3088,16 @@ function visitEach<T>(cb: NodeCallback<T>, nodes: readonly Node[] | undefined):
  * @param position Position
  * @param filter Filter if wanting to return a parent containing node early.
  */
+export function getNodeAtPosition(
```
Comment (timotheeguerin) [inline packages/compiler/core/parser.ts:3091]: do we need this overload, wouldn't TypeScript infer `node` if you don't pass `filter`?

Comment (nguerrera) [reply packages/compiler/core/parser.ts:3091]: I might not understand the suggestion, but I was trying to avoid making passing a filter that returns a boolean and is not a type predicate still work so there's no breaking change. If there's a way to have one overload and keep that compat, please let me know how and I'll gladly do it. :)

Comment (timotheeguerin) [reply packages/compiler/core/parser.ts:3091]: oh I was just wondering if this signature was not covering it all already(can we remove  the non templated one)

```
function getNodeAtPosition<T extends Node>(
  script: TypeSpecScriptNode,
  position: number,
  filter: (node: Node) => node is T
): T | undefined;
```

and we could just have that instead of the overloads but if you say that this caused backward compat issue then I  am probably wrong on what TypeScript can infer

File: packages/compiler/server/serverlib.ts [hunk 2]
```diff
@@ -1389,58 +1389,84 @@ type SignatureHelpNode =
...
+  }
+
+  // Don't provide signature help at the end position if it has a closing
+  // paren/angle bracket
+  if (position === node.end) {
+    const endChar = script.file.text.charCodeAt(position - 1);
+    const closingChar =
+      node.kind === SyntaxKind.TypeReference ? CharCode.GreaterThan : CharCode.CloseParen;
+    if (endChar === closingChar) {
+      return -1;
```
Comment (nguerrera) [inline packages/compiler/server/serverlib.ts:1461]: I think this should be moved where we check position > target.end to prevent a nested cursor right after an inner terminated list from getting chosen instead of the parent. Also, this check isn't robust as it will not account for unterminated list like `Foo<One, Foo<Two>`. I think we would need a flag from the parser to fix that.

File: packages/compiler/core/parser.ts (hunk 1 above)
Comment (nguerrera) [reply packages/compiler/core/parser.ts:3091]: I'll double check.

File: packages/compiler/server/serverlib.ts [hunk 3]
```diff
@@ -1389,58 +1389,84 @@ type SignatureHelpNode =
...
 function getSignatureHelpNodeAtPosition(
-  file: TypeSpecScriptNode,
+  script: TypeSpecScriptNode,
   position: number
 ): { node: SignatureHelpNode; argumentIndex: number } | undefined {
-  const node = getNodeAtPosition(file, position);
+  // Move back over any trailing whitespace. Otherwise, if there is no
+  // closing paren/angle bracket, we can find ourselves outside the desired
+  // node altogether in cases like `@dec(test, |`.
+  while (position > 0 && isWhiteSpace(script.file.text.charCodeAt(position - 1))) {
```
Comment (nguerrera) [inline packages/compiler/server/serverlib.ts:1398]: Ideally, this would skip all trailing trivia, not just whitespace. I think this will still fail with something like `@dec(a, b, /* hello * |`.I think the best approach would be to add getCommentAtPosition and use that. This could be a follow-up issue of lower priority. I don't think this use case is anywhere near as important as just a trailing `, ` with no close paren/angle bracket that this fixes.

Comment (bterlson) [reply packages/compiler/server/serverlib.ts:1398]: I'm not sure how getCommentAtPosition would help in this case? But agree some kind of previousNonTrivialToken helper would be good, fine if it's future.

**Review by bterlson — APPROVED** [review]

File: packages/compiler/core/parser.ts (hunk 1 above)
Comment (nguerrera) [reply packages/compiler/core/parser.ts:3108]: Confirming that would be a breaking change, unfortunately:

```
packages/compiler/server/serverlib.ts:1482:56 - error TS2345: Argument of type '(node: Node) => boolean' is not assignable to parameter of type '(node: Node) => node is Node'.
  Signature '(node: Node): boolean' must be a type predicate.

1482   const realNode = getNodeAtPosition(script, position, filter);
                                                            ~~~~~~
```

File: packages/compiler/server/serverlib.ts (hunk 3 above)
Comment (nguerrera) [reply packages/compiler/server/serverlib.ts:1398]: Filed #2012
