### PR TITLE
Fix stack overflow for specs with large number of circular references

### LINKED ISSUE #9603: [Bug]: typescpec model. RangeError: Maximum call stack size exceeded
### Describe the bug

Issue Title
Internal compiler error: RangeError: Maximum call stack size exceeded on large cyclic relationships (58+ models)

Issue Description
Describe the bug I encountered an internal compiler error (RangeError: Maximum call stack size exceeded) when compiling TypeSpec models generated from a Prisma schema. The error occurs when a central model (e.g., tb_user,tb_center) has circular relationships with a large number of other models (over 58 relations).

To Reproduce

Create a TypeSpec file where one model has circular references to 58+ other models.

Run the TypeSpec compiler.

The compiler fails with a stack overflow error.

Current Workaround: To bypass this error, I implemented a threshold in my generation script: if a model exceeds 30 relationships, I automatically replace the specific model references with Record<unknown>[] and use the @doc decorator to manually document the intended relation.

### Reproduction
[playground](https://typespec.io/playground/?e=%40typespec%2Fopenapi3&options=%7B%7D&vs=%7B%7D&c=Ly8gRGVuc2UgY2lyY3VsYXIgcmVmZXJlbmNlcyBwYXR0ZXJuIC0gZWFjaCBtb2RlbMwgbWFueSBvdGhlcnMKCsYeTcQGMSB7CiAgaWQ6IGludDMyOwogxDYxOsYeyBAyxxAzxxAzxxA0xxA0xxA1xxA1xxA2xxA2xxA3xxA3xxA4xxA4xxA5xxA5xxAxMMcRMTDIEjHIEugApDHpALXoAKYx6ACnMegAqDHoAKkx6ACqMegAqzHoAKwx6ACtMegArjHoAK8x6ACwMegAsTHoALIx6ACzMekAtMcRMugAs%2BkBRegAsugAnzLoALHoAJ4y6ACw6ACdMugArzY7Cn3tAbgy%2FQG4yWLPYdBgy1%2FtAbjoAPnoAQroAPfoAQjoAPXpAQboAajpAQXpAafpAbnpAKTpAbnpAafpAbnpAafpAbnpAafpAbnpAafpAbnpAafpAbnpAafpAbnpAafpALPwAbjpAafoALLpAUXoALHpAafoALDpAafoAK%2FoAJzpAbg38AG4M%2F0BuMliz2HQYMtf7QG46AD46AEJ6AD26QEH6AGo6QEG6AEH6QG56QCT6QG56QGn6QG56QGn6QG56QGn6QG56QGn6QG56QGn6QG56QGn6QG56QGn6QCy8AG46QCg6ACy6QGn6ACx6QFF6ACw6QGn6ACv6QGn6ACu6ACb6QG4OPABuDT9AbjJYs9h0GDLX%2B0BuOgA9%2BkBCOgBqOkBB%2BgBCOkBuegAg%2BkBuekBp%2BkBuekBp%2BkBuekBp%2BkBuekBp%2BkBuekBp%2BkBuekBp%2BkBuekBp%2BkAsfABuOkBIugAsekAn%2BgAsekBp%2BgAsOkBRegAr%2BkBp%2BgArukBp%2BgAregAmukBuDnwAbg1%2FQG4yWLPYdBgy1%2FtAbjpAajpAQjoAQnpAbnIc%2BkBuegBCekBuekBp%2BkBuekBp%2BkBuekBp%2BkBuekBp%2BkBuekBp%2BkBuekBp%2BkAsPABuOkBEegAsOkBp%2BgAsOkAnugAsOkBp%2BgAr%2BkBRegArukBp%2BgArekBp%2BgArOgAmekBuOQBSe4BuTb9AbnJY89i0GHMYO4BuugBC%2BkBushj6QG66AEL6QG66AEL6QG66QGo6QG66QGo6QG66QGo6QG66QGo6QG66QGo6QCv8AG56QEA6ACv6QGo6ACv6QGo6ACv6QCd6ACv6QGo6ACu6QFF6ACt6QGo6ACs6QGo6QCr6AFI6gG6MfABujf9AbrJZM9j0WLMYe4Bu8hT6QG76AEN6QG76AEN6QG76AEN6QG76QGp6QG76QGp6QG76QGp6QG76QGp6QCu8AG66QDv6ACu6QGp6ACu6QGp6ACu6QGp6ACu6QCc6ACu6QGp6ACt6QFF6ACs6QGp6QCr6QGp6QCr6QqZ6QFaMvABuzj9AbvJZdBk0WPMYu4BvOgBD%2BkBvOgBD%2BkBvOgBD%2BkBvOgBD%2BkBvOkBqukBvOkBqukBvOkBqukArfABu%2BkA3ugArekBqugArekBqugArekBqugArekBqugArekAm%2BgArekBqugArOkBRekAq%2BkBqukAq%2BkBqukBWekKnekBWjPwAbw5%2FQG8ymbQZdFkzGPuAb3oARHpAb3oARHpAb3oARHpAb3oARHpAb3pAavpAb3pAavpAKzwAbzpAM3oAKzpAavoAKzpAavoAKzpAavoAKzpAavoAKzpAavoAKzpAJroAKzpAavpAKvpAUXpAKvpAavpAVjpAavpAVnpCqLpAVo08AG9MTD%2BAb7JZ9Bm0WXMZO4BvugBE%2BkBvugBE%2BkBvugBE%2BkBvugBE%2BkBvukBrOkBE%2FABvfEPjvEPjfEPjPEPi%2FEPivEPifEPiPIPh%2BkBrPEQO%2BoBvukBrPEQO%2BoBvukKqOwQO%2B8Bvv4RRspn0GbRZcxk7gG%2B8BFL6QGt8RCc8RCb8BCa6QG98Q%2BT8Q%2BS8Q%2BR8Q%2BQ8Q%2BP8Q%2BO8Q%2BN8g%2BM6RHn8RBA6gG%2B8RFH6gGs8RBA6gG%2B8RFK5AFJ7wG%2B%2FhFMymfQZtFlzGTuAb7wEVHpAa3xEKHwEKDwEJ%2FpAb3xD5fxD5bxD5XxD5TxD5PxD5LyD5HpAazxEETqAb7xEUzqAUXxEEXqAb7xEU%2FpAUjqAb7xEVEx%2FhFSymfQZtFlzGTuAb7wEVfpAa3wEKbwEKXwEKTpAb3xD5vxD5rxD5nxD5jxD5fyD5bpAazxEEjqAb7xEVHqAazxEErqAb7xEVTqAazxEErqAb7xEVcx%2FhFYymfQZtFlzGTuAb7xEV3vAb3wD6LwD6HxD6DxD5%2FxD57xD53xD5zyD5vpAazxEEzqAb7xEVbqEfbxEE%2FqAb7xEVnqAazxEE%2FqAb7xEVzkAUnvAb7%2BEV7KZ9Bm0WXMZO4Bvu8BvfAPpvAPpfAPpPEPo%2FEPovEPofEPoPIPn%2BkBrPEQT%2BoBvvERW%2BoBrPEQUuoBvvERXuoBRfEQU%2BoBvvERYekBSOoBvvEBvf4RYspm0GXRZMtj7QG88A%2Bo8A%2Bn8A%2Bm8A%2Bl8Q%2Bk8Q%2Bj8Q%2Bi8g%2Bh6QGr8RBQ6gG98RFe6gGr8RBT6gG98RFh6gGr8RBV6gG98RFk6gGr8BBV6QG88Q%2BoMf4RZMpl0GTQY8ti7QG78A%2Bn8A%2Bm8A%2Bl8A%2Bk8Q%2Bj8Q%2Bi8g%2Bh6QGq8RBP6gG88RFf6gGq8RBS6gG88RFi6hH%2F8RBV6gG88RFl6gGq8BBV6QG78Q%2Bo8Q%2BnMf4RZMpkz2PQYsth7QG68A%2Bk8A%2Bj8A%2Bi8A%2Bh8Q%2Bg8g%2Bf6QGp8RBM6gG78RFe6gGp8RBP6gG78RFh6gGp8RBS6gG78RFk6gFF8BBT6QG68Q%2Bm8Q%2Bl8g%2Bk%2FxFi7wG58A%2Bi8A%2Bh8A%2Bg8A%2Bf8A%2Be8A%2Bd8A%2Bc8g%2Bb6QGo8RBH6gG68RFb6gGo8RBK6gG68RFe6gGo8RBN6gG68RFh6gGo8BBP6QG58Q%2Bi8Q%2Bh8Q%2Bg5Q%2Bf)

Playground Error: URI  too long

My Typespec Code
https://anotepad.com/note/read/bq9bbwef

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #9603

### CODE REVIEW

File: packages/compiler/src/core/name-resolver.ts [hunk 1]
```diff
@@ -1217,6 +1218,15 @@ export function createResolver(program: Program): NameResolver {
...
 
   function bindAndResolveNode(node: Node) {
+    if (visitedNode.has(node)) {
+      return;
+    }
+    visitedNode.add(node);
+
+    if ("id" in node && node.kind !== SyntaxKind.MemberExpression && node.id) {
+      bindDeclarationIdentifier(node as any);
+    }
```
Comment (timotheeguerin) [inline packages/compiler/src/core/name-resolver.ts:1228]: having this after the resolveTypeReference would actually create an issue with symbol not linking to the right one(it seems like it worked before because we kept rebinding so it picked it up correctly)
