### PR TITLE
[Compiler] Fix error message for bad '@encode' with unixTimestamp

### LINKED ISSUE #2394: error msg of unixTimestamp encoding is misleading
When I write something like below in the playground,
```
model Foo {
  @encode(DateTimeKnownEncoding.unixTimestamp)
  prop1: utcDateTime;
}
```
I got an error message like
image

But the actual fix is that we need an encodedAs scalar as the second parameter for encode in the case of unixTimestamp.
```
model Foo {
  @encode(DateTimeKnownEncoding.unixTimestamp, int64)
  prop1: utcDateTime;
}
```

Also, should we consider set a default encodedAs scalar for unixTimestamp encoding ?

### PR DESCRIPTION
**Pull request by tjprescott**
Fix #2394.

### CODE REVIEW

File: packages/compiler/src/core/messages.ts [hunk 1]
```diff
@@ -736,6 +736,7 @@ const diagnostics = {
       default: "Invalid encoding",
       wrongType: paramMessage`Encoding '${"encoding"}' cannot be used on type '${"type"}'. Expected: ${"expected"}.`,
       wrongEncodingType: paramMessage`Encoding '${"encoding"}' on type '${"type"}' is expected to be serialized as '${"expected"}' but got '${"actual"}'.`,
+      wrongUnixTimestampEncoding: paramMessage`Encoding '${"encoding"}' on type '${"type"}' is expected to be serialized as '${"expected"}' but got '${"actual"}'. Set '@encode' 2nd parameter to be an integer. e.g. '@encode("unixTimestamp", int32)'`,
```
Comment (timotheeguerin) [inline packages/compiler/src/core/messages.ts:739]: Wondering if we should have a more generic explaination, This was reported to be the same problem for duration with `seconds` encoding

Comment (tjprescott) [reply packages/compiler/src/core/messages.ts:739]: I can just do it for all the non-string encodings?

Comment (timotheeguerin) [reply packages/compiler/src/core/messages.ts:739]: yeah I think that would be great

**Review by timotheeguerin — APPROVED** [review]
