### PR TITLE
Fix: Literal unions with the same variants keep adding duplicate entries

### LINKED ISSUE #3087: [Bug]: OpenAPI3 Enum duplicating literal values when inheriting
### Describe the bug

When I have multiple models ~using inheritance,~ that each have an enum of literal numbers, the final value (emitted as OpenAPI3) duplicates itself depending on how many models I have: 

```
model SecondModel extends BaseModel {
  active: 0 | 1;
}
```

```
active:
  type: number
  enum:
    - 0
    - 1
    - 1
    - 1
    - 1
```

### Reproduction

~[Playground Link](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZb3BlbmFwaTMiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFU9wZW5BUEk7Cgptb2RlbCBCYXNlTcUKewogIGlkOiBpbnRlZ2VyOwogIHNvbWV0aGluZzogMCB8IDE7Cn3IOEZpcnN0xjlleHRlbmRzz0tuYW1lOiBzdHJpbmfETGFjdGl2ZdJJU2Vjb25k3ErYOlRoaXLfOc85&e=%40typespec%2Fopenapi3&options=%7B%7D)~ There's a [simpler version](https://typespec.io/playground?c=bW9kZWwgQSB7CiAgc29tZXRoaW5nOiAwIHwgMTsKfQoKxiFCIMUiYWN0aXZl0h9D3h9E1x8%3D&e=%40typespec%2Fopenapi3&options=%7B%7D) 

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #3087

### CODE REVIEW

File: packages/openapi3/src/schema-emitter.ts [hunk 1]
```diff
@@ -465,13 +465,15 @@ export class OpenAPI3SchemaEmitter extends TypeEmitter<
   }
 
   #unionSchema(union: Union): ObjectBuilder<OpenAPI3Schema> {
+    console.log("Variants: ", union.name);
```
Comment (bterlson) [inline packages/openapi3/src/schema-emitter.ts:468]:
```suggestion
```
